// Generated by CIRCT firtool-1.135.0
module Arbiter4_L2CacheErrorInfo(
  input         io_in_0_valid,
  input         io_in_0_bits_valid,
  input  [45:0] io_in_0_bits_address,
  input         io_in_1_valid,
  input         io_in_1_bits_valid,
  input  [45:0] io_in_1_bits_address,
  input         io_in_2_valid,
  input         io_in_2_bits_valid,
  input  [45:0] io_in_2_bits_address,
  input         io_in_3_valid,
  input         io_in_3_bits_valid,
  input  [45:0] io_in_3_bits_address,
  output        io_out_valid,
  output        io_out_bits_valid,
  output [45:0] io_out_bits_address
);

  assign io_out_valid = io_in_0_valid | io_in_1_valid | io_in_2_valid | io_in_3_valid;
  assign io_out_bits_valid =
    io_in_0_valid
      ? io_in_0_bits_valid
      : io_in_1_valid
          ? io_in_1_bits_valid
          : io_in_2_valid ? io_in_2_bits_valid : io_in_3_bits_valid;
  assign io_out_bits_address =
    io_in_0_valid
      ? io_in_0_bits_address
      : io_in_1_valid
          ? io_in_1_bits_address
          : io_in_2_valid ? io_in_2_bits_address : io_in_3_bits_address;
endmodule

