// Generated by CIRCT firtool-1.135.0
module Arbiter5_PrefetchReq(
  input         io_in_0_valid,
  input  [31:0] io_in_0_bits_tag,
  input  [9:0]  io_in_0_bits_set,
  input  [4:0]  io_in_0_bits_pfSource,
  input         io_in_2_valid,
  input  [31:0] io_in_2_bits_tag,
  input  [9:0]  io_in_2_bits_set,
  input  [43:0] io_in_2_bits_vaddr,
  input         io_in_2_bits_needT,
  input  [6:0]  io_in_2_bits_source,
  input         io_in_3_valid,
  input  [31:0] io_in_3_bits_tag,
  input  [9:0]  io_in_3_bits_set,
  input  [43:0] io_in_3_bits_vaddr,
  input         io_in_3_bits_needT,
  input  [6:0]  io_in_3_bits_source,
  output        io_out_valid,
  output [31:0] io_out_bits_tag,
  output [9:0]  io_out_bits_set,
  output [43:0] io_out_bits_vaddr,
  output        io_out_bits_needT,
  output [6:0]  io_out_bits_source,
  output [4:0]  io_out_bits_pfSource
);

  assign io_out_valid = io_in_0_valid | io_in_2_valid | io_in_3_valid;
  assign io_out_bits_tag =
    io_in_0_valid
      ? io_in_0_bits_tag
      : io_in_2_valid ? io_in_2_bits_tag : io_in_3_valid ? io_in_3_bits_tag : 32'h0;
  assign io_out_bits_set =
    io_in_0_valid
      ? io_in_0_bits_set
      : io_in_2_valid ? io_in_2_bits_set : io_in_3_valid ? io_in_3_bits_set : 10'h0;
  assign io_out_bits_vaddr =
    io_in_0_valid
      ? 44'h0
      : io_in_2_valid ? io_in_2_bits_vaddr : io_in_3_valid ? io_in_3_bits_vaddr : 44'h0;
  assign io_out_bits_needT =
    ~io_in_0_valid
    & (io_in_2_valid ? io_in_2_bits_needT : io_in_3_valid & io_in_3_bits_needT);
  assign io_out_bits_source =
    io_in_0_valid
      ? 7'h0
      : io_in_2_valid ? io_in_2_bits_source : io_in_3_valid ? io_in_3_bits_source : 7'h0;
  assign io_out_bits_pfSource =
    io_in_0_valid
      ? io_in_0_bits_pfSource
      : io_in_2_valid ? 5'h8 : io_in_3_valid ? 5'h9 : 5'h0;
endmodule

