// Generated by CIRCT firtool-1.135.0
module Arbiter4_L2ToL1Hint(
  output       io_in_0_ready,
  input        io_in_0_valid,
  input  [6:0] io_in_0_bits_sourceId,
  input        io_in_0_bits_isKeyword,
  output       io_in_1_ready,
  input        io_in_1_valid,
  input  [6:0] io_in_1_bits_sourceId,
  input        io_in_1_bits_isKeyword,
  output       io_in_2_ready,
  input        io_in_2_valid,
  input  [6:0] io_in_2_bits_sourceId,
  input        io_in_2_bits_isKeyword,
  output       io_in_3_ready,
  input        io_in_3_valid,
  input  [6:0] io_in_3_bits_sourceId,
  input        io_in_3_bits_isKeyword,
  input        io_out_ready,
  output       io_out_valid,
  output [6:0] io_out_bits_sourceId,
  output       io_out_bits_isKeyword,
  output [1:0] io_chosen
);

  wire _grant_T = io_in_0_valid | io_in_1_valid;
  wire _io_out_valid_T = _grant_T | io_in_2_valid;
  assign io_in_0_ready = io_out_ready;
  assign io_in_1_ready = ~io_in_0_valid & io_out_ready;
  assign io_in_2_ready = ~_grant_T & io_out_ready;
  assign io_in_3_ready = ~_io_out_valid_T & io_out_ready;
  assign io_out_valid = _io_out_valid_T | io_in_3_valid;
  assign io_out_bits_sourceId =
    io_in_0_valid
      ? io_in_0_bits_sourceId
      : io_in_1_valid
          ? io_in_1_bits_sourceId
          : io_in_2_valid ? io_in_2_bits_sourceId : io_in_3_bits_sourceId;
  assign io_out_bits_isKeyword =
    io_in_0_valid
      ? io_in_0_bits_isKeyword
      : io_in_1_valid
          ? io_in_1_bits_isKeyword
          : io_in_2_valid ? io_in_2_bits_isKeyword : io_in_3_bits_isKeyword;
  assign io_chosen = io_in_0_valid ? 2'h0 : io_in_1_valid ? 2'h1 : {1'h1, ~io_in_2_valid};
endmodule

