// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS


// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
// VCS coverage exclude_file
module array_128x38(
  input  [6:0]  RW0_addr,
  input         RW0_en,
  input         RW0_clk,
  input         RW0_wmode,
  input  [37:0] RW0_wdata,
  output [37:0] RW0_rdata,
  input  [37:0] RW0_wmask
);

  reg [37:0] Memory[0:127];
  reg [6:0]  _RW0_raddr_d0;
  reg        _RW0_rmode_d0;
  always @(posedge RW0_clk) begin
    if (RW0_en)
      _RW0_raddr_d0 <= RW0_addr;
    _RW0_rmode_d0 <= RW0_wmode;
    if (RW0_en & RW0_wmask[0] & RW0_wmode)
      Memory[RW0_addr][32'h0 +: 1] <= RW0_wdata[0];
    if (RW0_en & RW0_wmask[1] & RW0_wmode)
      Memory[RW0_addr][32'h1 +: 1] <= RW0_wdata[1];
    if (RW0_en & RW0_wmask[2] & RW0_wmode)
      Memory[RW0_addr][32'h2 +: 1] <= RW0_wdata[2];
    if (RW0_en & RW0_wmask[3] & RW0_wmode)
      Memory[RW0_addr][32'h3 +: 1] <= RW0_wdata[3];
    if (RW0_en & RW0_wmask[4] & RW0_wmode)
      Memory[RW0_addr][32'h4 +: 1] <= RW0_wdata[4];
    if (RW0_en & RW0_wmask[5] & RW0_wmode)
      Memory[RW0_addr][32'h5 +: 1] <= RW0_wdata[5];
    if (RW0_en & RW0_wmask[6] & RW0_wmode)
      Memory[RW0_addr][32'h6 +: 1] <= RW0_wdata[6];
    if (RW0_en & RW0_wmask[7] & RW0_wmode)
      Memory[RW0_addr][32'h7 +: 1] <= RW0_wdata[7];
    if (RW0_en & RW0_wmask[8] & RW0_wmode)
      Memory[RW0_addr][32'h8 +: 1] <= RW0_wdata[8];
    if (RW0_en & RW0_wmask[9] & RW0_wmode)
      Memory[RW0_addr][32'h9 +: 1] <= RW0_wdata[9];
    if (RW0_en & RW0_wmask[10] & RW0_wmode)
      Memory[RW0_addr][32'hA +: 1] <= RW0_wdata[10];
    if (RW0_en & RW0_wmask[11] & RW0_wmode)
      Memory[RW0_addr][32'hB +: 1] <= RW0_wdata[11];
    if (RW0_en & RW0_wmask[12] & RW0_wmode)
      Memory[RW0_addr][32'hC +: 1] <= RW0_wdata[12];
    if (RW0_en & RW0_wmask[13] & RW0_wmode)
      Memory[RW0_addr][32'hD +: 1] <= RW0_wdata[13];
    if (RW0_en & RW0_wmask[14] & RW0_wmode)
      Memory[RW0_addr][32'hE +: 1] <= RW0_wdata[14];
    if (RW0_en & RW0_wmask[15] & RW0_wmode)
      Memory[RW0_addr][32'hF +: 1] <= RW0_wdata[15];
    if (RW0_en & RW0_wmask[16] & RW0_wmode)
      Memory[RW0_addr][32'h10 +: 1] <= RW0_wdata[16];
    if (RW0_en & RW0_wmask[17] & RW0_wmode)
      Memory[RW0_addr][32'h11 +: 1] <= RW0_wdata[17];
    if (RW0_en & RW0_wmask[18] & RW0_wmode)
      Memory[RW0_addr][32'h12 +: 1] <= RW0_wdata[18];
    if (RW0_en & RW0_wmask[19] & RW0_wmode)
      Memory[RW0_addr][32'h13 +: 1] <= RW0_wdata[19];
    if (RW0_en & RW0_wmask[20] & RW0_wmode)
      Memory[RW0_addr][32'h14 +: 1] <= RW0_wdata[20];
    if (RW0_en & RW0_wmask[21] & RW0_wmode)
      Memory[RW0_addr][32'h15 +: 1] <= RW0_wdata[21];
    if (RW0_en & RW0_wmask[22] & RW0_wmode)
      Memory[RW0_addr][32'h16 +: 1] <= RW0_wdata[22];
    if (RW0_en & RW0_wmask[23] & RW0_wmode)
      Memory[RW0_addr][32'h17 +: 1] <= RW0_wdata[23];
    if (RW0_en & RW0_wmask[24] & RW0_wmode)
      Memory[RW0_addr][32'h18 +: 1] <= RW0_wdata[24];
    if (RW0_en & RW0_wmask[25] & RW0_wmode)
      Memory[RW0_addr][32'h19 +: 1] <= RW0_wdata[25];
    if (RW0_en & RW0_wmask[26] & RW0_wmode)
      Memory[RW0_addr][32'h1A +: 1] <= RW0_wdata[26];
    if (RW0_en & RW0_wmask[27] & RW0_wmode)
      Memory[RW0_addr][32'h1B +: 1] <= RW0_wdata[27];
    if (RW0_en & RW0_wmask[28] & RW0_wmode)
      Memory[RW0_addr][32'h1C +: 1] <= RW0_wdata[28];
    if (RW0_en & RW0_wmask[29] & RW0_wmode)
      Memory[RW0_addr][32'h1D +: 1] <= RW0_wdata[29];
    if (RW0_en & RW0_wmask[30] & RW0_wmode)
      Memory[RW0_addr][32'h1E +: 1] <= RW0_wdata[30];
    if (RW0_en & RW0_wmask[31] & RW0_wmode)
      Memory[RW0_addr][32'h1F +: 1] <= RW0_wdata[31];
    if (RW0_en & RW0_wmask[32] & RW0_wmode)
      Memory[RW0_addr][32'h20 +: 1] <= RW0_wdata[32];
    if (RW0_en & RW0_wmask[33] & RW0_wmode)
      Memory[RW0_addr][32'h21 +: 1] <= RW0_wdata[33];
    if (RW0_en & RW0_wmask[34] & RW0_wmode)
      Memory[RW0_addr][32'h22 +: 1] <= RW0_wdata[34];
    if (RW0_en & RW0_wmask[35] & RW0_wmode)
      Memory[RW0_addr][32'h23 +: 1] <= RW0_wdata[35];
    if (RW0_en & RW0_wmask[36] & RW0_wmode)
      Memory[RW0_addr][32'h24 +: 1] <= RW0_wdata[36];
    if (RW0_en & RW0_wmask[37] & RW0_wmode)
      Memory[RW0_addr][32'h25 +: 1] <= RW0_wdata[37];
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_
    `ifdef RANDOMIZE_REG_INIT
      reg [31:0] _RANDOM;
    `endif // RANDOMIZE_REG_INIT
    reg [63:0] _RANDOM_MEM;
    initial begin
      `INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_MEM_INIT
        for (logic [7:0] i = 8'h0; i < 8'h80; i += 8'h1) begin
          for (logic [6:0] j = 7'h0; j < 7'h40; j += 7'h20) begin
            _RANDOM_MEM[j[5:0] +: 32] = `RANDOM;
          end
          Memory[i[6:0]] = _RANDOM_MEM[37:0];
        end
      `endif // RANDOMIZE_MEM_INIT
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM = {`RANDOM};
        _RW0_raddr_d0 = _RANDOM[6:0];
        _RW0_rmode_d0 = _RANDOM[7];
      `endif // RANDOMIZE_REG_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign RW0_rdata = Memory[_RW0_raddr_d0];
endmodule

