// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS


// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
// VCS coverage exclude_file
module array_128x192(
  input  [6:0]   RW0_addr,
  input          RW0_en,
  input          RW0_clk,
  input          RW0_wmode,
  input  [191:0] RW0_wdata,
  output [191:0] RW0_rdata,
  input  [31:0]  RW0_wmask
);

  reg [191:0] Memory[0:127];
  reg [6:0]   _RW0_raddr_d0;
  reg         _RW0_rmode_d0;
  always @(posedge RW0_clk) begin
    if (RW0_en)
      _RW0_raddr_d0 <= RW0_addr;
    _RW0_rmode_d0 <= RW0_wmode;
    if (RW0_en & RW0_wmask[0] & RW0_wmode)
      Memory[RW0_addr][32'h0 +: 6] <= RW0_wdata[5:0];
    if (RW0_en & RW0_wmask[1] & RW0_wmode)
      Memory[RW0_addr][32'h6 +: 6] <= RW0_wdata[11:6];
    if (RW0_en & RW0_wmask[2] & RW0_wmode)
      Memory[RW0_addr][32'hC +: 6] <= RW0_wdata[17:12];
    if (RW0_en & RW0_wmask[3] & RW0_wmode)
      Memory[RW0_addr][32'h12 +: 6] <= RW0_wdata[23:18];
    if (RW0_en & RW0_wmask[4] & RW0_wmode)
      Memory[RW0_addr][32'h18 +: 6] <= RW0_wdata[29:24];
    if (RW0_en & RW0_wmask[5] & RW0_wmode)
      Memory[RW0_addr][32'h1E +: 6] <= RW0_wdata[35:30];
    if (RW0_en & RW0_wmask[6] & RW0_wmode)
      Memory[RW0_addr][32'h24 +: 6] <= RW0_wdata[41:36];
    if (RW0_en & RW0_wmask[7] & RW0_wmode)
      Memory[RW0_addr][32'h2A +: 6] <= RW0_wdata[47:42];
    if (RW0_en & RW0_wmask[8] & RW0_wmode)
      Memory[RW0_addr][32'h30 +: 6] <= RW0_wdata[53:48];
    if (RW0_en & RW0_wmask[9] & RW0_wmode)
      Memory[RW0_addr][32'h36 +: 6] <= RW0_wdata[59:54];
    if (RW0_en & RW0_wmask[10] & RW0_wmode)
      Memory[RW0_addr][32'h3C +: 6] <= RW0_wdata[65:60];
    if (RW0_en & RW0_wmask[11] & RW0_wmode)
      Memory[RW0_addr][32'h42 +: 6] <= RW0_wdata[71:66];
    if (RW0_en & RW0_wmask[12] & RW0_wmode)
      Memory[RW0_addr][32'h48 +: 6] <= RW0_wdata[77:72];
    if (RW0_en & RW0_wmask[13] & RW0_wmode)
      Memory[RW0_addr][32'h4E +: 6] <= RW0_wdata[83:78];
    if (RW0_en & RW0_wmask[14] & RW0_wmode)
      Memory[RW0_addr][32'h54 +: 6] <= RW0_wdata[89:84];
    if (RW0_en & RW0_wmask[15] & RW0_wmode)
      Memory[RW0_addr][32'h5A +: 6] <= RW0_wdata[95:90];
    if (RW0_en & RW0_wmask[16] & RW0_wmode)
      Memory[RW0_addr][32'h60 +: 6] <= RW0_wdata[101:96];
    if (RW0_en & RW0_wmask[17] & RW0_wmode)
      Memory[RW0_addr][32'h66 +: 6] <= RW0_wdata[107:102];
    if (RW0_en & RW0_wmask[18] & RW0_wmode)
      Memory[RW0_addr][32'h6C +: 6] <= RW0_wdata[113:108];
    if (RW0_en & RW0_wmask[19] & RW0_wmode)
      Memory[RW0_addr][32'h72 +: 6] <= RW0_wdata[119:114];
    if (RW0_en & RW0_wmask[20] & RW0_wmode)
      Memory[RW0_addr][32'h78 +: 6] <= RW0_wdata[125:120];
    if (RW0_en & RW0_wmask[21] & RW0_wmode)
      Memory[RW0_addr][32'h7E +: 6] <= RW0_wdata[131:126];
    if (RW0_en & RW0_wmask[22] & RW0_wmode)
      Memory[RW0_addr][32'h84 +: 6] <= RW0_wdata[137:132];
    if (RW0_en & RW0_wmask[23] & RW0_wmode)
      Memory[RW0_addr][32'h8A +: 6] <= RW0_wdata[143:138];
    if (RW0_en & RW0_wmask[24] & RW0_wmode)
      Memory[RW0_addr][32'h90 +: 6] <= RW0_wdata[149:144];
    if (RW0_en & RW0_wmask[25] & RW0_wmode)
      Memory[RW0_addr][32'h96 +: 6] <= RW0_wdata[155:150];
    if (RW0_en & RW0_wmask[26] & RW0_wmode)
      Memory[RW0_addr][32'h9C +: 6] <= RW0_wdata[161:156];
    if (RW0_en & RW0_wmask[27] & RW0_wmode)
      Memory[RW0_addr][32'hA2 +: 6] <= RW0_wdata[167:162];
    if (RW0_en & RW0_wmask[28] & RW0_wmode)
      Memory[RW0_addr][32'hA8 +: 6] <= RW0_wdata[173:168];
    if (RW0_en & RW0_wmask[29] & RW0_wmode)
      Memory[RW0_addr][32'hAE +: 6] <= RW0_wdata[179:174];
    if (RW0_en & RW0_wmask[30] & RW0_wmode)
      Memory[RW0_addr][32'hB4 +: 6] <= RW0_wdata[185:180];
    if (RW0_en & RW0_wmask[31] & RW0_wmode)
      Memory[RW0_addr][32'hBA +: 6] <= RW0_wdata[191:186];
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_
    `ifdef RANDOMIZE_REG_INIT
      reg [31:0] _RANDOM;
    `endif // RANDOMIZE_REG_INIT
    reg [191:0] _RANDOM_MEM;
    initial begin
      `INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_MEM_INIT
        for (logic [7:0] i = 8'h0; i < 8'h80; i += 8'h1) begin
          for (logic [7:0] j = 8'h0; j < 8'hC0; j += 8'h20) begin
            _RANDOM_MEM[j +: 32] = `RANDOM;
          end
          Memory[i[6:0]] = _RANDOM_MEM;
        end
      `endif // RANDOMIZE_MEM_INIT
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM = {`RANDOM};
        _RW0_raddr_d0 = _RANDOM[6:0];
        _RW0_rmode_d0 = _RANDOM[7];
      `endif // RANDOMIZE_REG_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign RW0_rdata = Memory[_RW0_raddr_d0];
endmodule

