// Generated by CIRCT firtool-1.135.0
module AsyncResetSynchronizerShiftReg_w1_d3_i0(
  input  clock,
  input  reset,
  input  io_d,
  output io_q
);

  AsyncResetSynchronizerPrimitiveShiftReg_d3_i0 output_chain (
    .clock (clock),
    .reset (reset),
    .io_d  (io_d),
    .io_q  (io_q)
  );
endmodule

