// Generated by CIRCT firtool-1.135.0
module CustomL1Hint(
  input        clock,
  input        reset,
  input        io_mshrHintQInfo_valid,
  input  [2:0] io_mshrHintQInfo_bits_channel,
  input        io_mshrHintQInfo_bits_isKeyword,
  input  [3:0] io_mshrHintQInfo_bits_opcode,
  input  [6:0] io_mshrHintQInfo_bits_sourceId,
  input        io_mshrHintQInfo_bits_mergeA,
  input        io_mshrHintQInfo_bits_aMergeTask_isKeyword,
  input  [2:0] io_mshrHintQInfo_bits_aMergeTask_opcode,
  input  [6:0] io_mshrHintQInfo_bits_aMergeTask_sourceId,
  input        io_sinkCHintQInfo_valid,
  input  [6:0] io_sinkCHintQInfo_bits_sourceId,
  input        io_s3_task_valid,
  input  [2:0] io_s3_task_bits_channel,
  input        io_s3_task_bits_isKeyword,
  input  [3:0] io_s3_task_bits_opcode,
  input  [6:0] io_s3_task_bits_sourceId,
  input        io_s3_task_bits_mshrTask,
  input        io_s3_need_mshr,
  input        io_l1Hint_ready,
  output       io_l1Hint_valid,
  output [6:0] io_l1Hint_bits_sourceId,
  output       io_l1Hint_bits_isKeyword
);

  wire       _Hint_arb_io_in_1_ready;
  wire       _Hint_arb_io_in_2_ready;
  wire       _Hint_arb_io_out_valid;
  wire [6:0] _Hint_arb_io_out_bits_source;
  wire       _Hint_arb_io_out_bits_isGrantData;
  wire       _Hint_arb_io_out_bits_isKeyword;
  wire       _hint_s1Queue_io_out_valid;
  wire [6:0] _hint_s1Queue_io_out_bits_source;
  wire       _hint_s1Queue_io_out_bits_isGrantData;
  wire       _hint_s1Queue_io_out_bits_isKeyword;
  wire       _hintQueue_io_enq_ready;
  wire       _hintQueue_io_deq_valid;
  wire       _hintQueue_io_deq_bits_isGrantData;
  wire [4:0] _hintQueue_io_count;
  wire       mshr_GrantData_s1 =
    io_mshrHintQInfo_valid & io_mshrHintQInfo_bits_channel[0]
    & (io_mshrHintQInfo_bits_opcode == 4'h5 | io_mshrHintQInfo_bits_mergeA
       & io_mshrHintQInfo_bits_aMergeTask_opcode == 3'h5);
  wire [6:0] enqBits_s1_source =
    (io_mshrHintQInfo_valid & io_mshrHintQInfo_bits_mergeA
       ? io_mshrHintQInfo_bits_aMergeTask_sourceId
       : 7'h0)
    | (io_mshrHintQInfo_valid & ~io_mshrHintQInfo_bits_mergeA
         ? io_mshrHintQInfo_bits_sourceId
         : 7'h0) | (io_sinkCHintQInfo_valid ? io_sinkCHintQInfo_bits_sourceId : 7'h0);
  wire       enqBits_s1_isKeyword =
    io_mshrHintQInfo_bits_mergeA
      ? io_mshrHintQInfo_bits_aMergeTask_isKeyword
      : io_mshrHintQInfo_bits_isKeyword;
  wire       chn_GrantData_s3 =
    io_s3_task_valid & ~io_s3_task_bits_mshrTask & ~io_s3_need_mshr
    & io_s3_task_bits_channel[0] & io_s3_task_bits_opcode == 4'h5;
  wire       canFlow_s1 =
    ~_hintQueue_io_deq_valid | _hintQueue_io_count == 5'h1 & io_l1Hint_ready
    & _hintQueue_io_deq_valid;
  wire       valid_s1 =
    mshr_GrantData_s1 | io_mshrHintQInfo_valid & io_mshrHintQInfo_bits_channel[0]
    & (io_mshrHintQInfo_bits_opcode == 4'h4 | io_mshrHintQInfo_bits_mergeA
       & io_mshrHintQInfo_bits_aMergeTask_opcode == 3'h4) | io_sinkCHintQInfo_valid;
  Queue16_HintQueueEntry hintQueue (
    .clock                   (clock),
    .reset                   (reset),
    .io_enq_ready            (_hintQueue_io_enq_ready),
    .io_enq_valid            (_Hint_arb_io_out_valid),
    .io_enq_bits_source      (_Hint_arb_io_out_bits_source),
    .io_enq_bits_isGrantData (_Hint_arb_io_out_bits_isGrantData),
    .io_enq_bits_isKeyword   (_Hint_arb_io_out_bits_isKeyword),
    .io_deq_ready            (io_l1Hint_ready),
    .io_deq_valid            (_hintQueue_io_deq_valid),
    .io_deq_bits_source      (io_l1Hint_bits_sourceId),
    .io_deq_bits_isGrantData (_hintQueue_io_deq_bits_isGrantData),
    .io_deq_bits_isKeyword   (io_l1Hint_bits_isKeyword),
    .io_count                (_hintQueue_io_count)
  );
  Pipeline_4 hint_s1Queue (
    .clock                   (clock),
    .reset                   (reset),
    .io_in_valid             (valid_s1 & (~canFlow_s1 | ~_Hint_arb_io_in_2_ready)),
    .io_in_bits_source       (enqBits_s1_source),
    .io_in_bits_isGrantData  (mshr_GrantData_s1),
    .io_in_bits_isKeyword    (enqBits_s1_isKeyword),
    .io_out_ready            (_Hint_arb_io_in_1_ready),
    .io_out_valid            (_hint_s1Queue_io_out_valid),
    .io_out_bits_source      (_hint_s1Queue_io_out_bits_source),
    .io_out_bits_isGrantData (_hint_s1Queue_io_out_bits_isGrantData),
    .io_out_bits_isKeyword   (_hint_s1Queue_io_out_bits_isKeyword)
  );
  Arbiter3_HintQueueEntry Hint_arb (
    .io_in_0_valid
      (io_s3_task_valid & ~io_s3_task_bits_mshrTask & ~io_s3_need_mshr
       & io_s3_task_bits_channel[0] & io_s3_task_bits_opcode == 4'h4 | chn_GrantData_s3),
    .io_in_0_bits_source      (io_s3_task_bits_sourceId),
    .io_in_0_bits_isGrantData (chn_GrantData_s3),
    .io_in_0_bits_isKeyword   (io_s3_task_bits_isKeyword),
    .io_in_1_ready            (_Hint_arb_io_in_1_ready),
    .io_in_1_valid            (_hint_s1Queue_io_out_valid),
    .io_in_1_bits_source      (_hint_s1Queue_io_out_bits_source),
    .io_in_1_bits_isGrantData (_hint_s1Queue_io_out_bits_isGrantData),
    .io_in_1_bits_isKeyword   (_hint_s1Queue_io_out_bits_isKeyword),
    .io_in_2_ready            (_Hint_arb_io_in_2_ready),
    .io_in_2_valid            (valid_s1 & canFlow_s1),
    .io_in_2_bits_source      (enqBits_s1_source),
    .io_in_2_bits_isGrantData (mshr_GrantData_s1),
    .io_in_2_bits_isKeyword   (enqBits_s1_isKeyword),
    .io_out_ready             (_hintQueue_io_enq_ready),
    .io_out_valid             (_Hint_arb_io_out_valid),
    .io_out_bits_source       (_Hint_arb_io_out_bits_source),
    .io_out_bits_isGrantData  (_Hint_arb_io_out_bits_isGrantData),
    .io_out_bits_isKeyword    (_Hint_arb_io_out_bits_isKeyword)
  );
  assign io_l1Hint_valid = _hintQueue_io_deq_valid & _hintQueue_io_deq_bits_isGrantData;
endmodule

