// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module FastArbiter_64(
  input         clock,
  input         reset,
  output        io_in_0_ready,
  input         io_in_0_valid,
  input  [3:0]  io_in_0_bits_qos,
  input  [11:0] io_in_0_bits_txnID,
  input  [10:0] io_in_0_bits_returnNID,
  input         io_in_0_bits_stashNIDValid,
  input  [11:0] io_in_0_bits_returnTxnID,
  input  [6:0]  io_in_0_bits_opcode,
  input  [47:0] io_in_0_bits_addr,
  input         io_in_0_bits_ns,
  input         io_in_0_bits_likelyshared,
  input         io_in_0_bits_allowRetry,
  input  [1:0]  io_in_0_bits_order,
  input  [3:0]  io_in_0_bits_pCrdType,
  input         io_in_0_bits_memAttr_allocate,
  input         io_in_0_bits_memAttr_cacheable,
  input         io_in_0_bits_memAttr_device,
  input         io_in_0_bits_memAttr_ewa,
  input         io_in_0_bits_snpAttr,
  input  [7:0]  io_in_0_bits_lpIDWithPadding,
  input         io_in_0_bits_snoopMe,
  input         io_in_0_bits_expCompAck,
  input  [1:0]  io_in_0_bits_tagOp,
  input         io_in_0_bits_traceTag,
  input         io_in_0_bits_mpam_perfMonGroup,
  input  [8:0]  io_in_0_bits_mpam_partID,
  input         io_in_0_bits_mpam_mpamNS,
  input  [3:0]  io_in_0_bits_rsvdc,
  output        io_in_1_ready,
  input         io_in_1_valid,
  input  [3:0]  io_in_1_bits_qos,
  input  [11:0] io_in_1_bits_txnID,
  input  [10:0] io_in_1_bits_returnNID,
  input         io_in_1_bits_stashNIDValid,
  input  [11:0] io_in_1_bits_returnTxnID,
  input  [6:0]  io_in_1_bits_opcode,
  input  [47:0] io_in_1_bits_addr,
  input         io_in_1_bits_ns,
  input         io_in_1_bits_likelyshared,
  input         io_in_1_bits_allowRetry,
  input  [1:0]  io_in_1_bits_order,
  input  [3:0]  io_in_1_bits_pCrdType,
  input         io_in_1_bits_memAttr_allocate,
  input         io_in_1_bits_memAttr_cacheable,
  input         io_in_1_bits_memAttr_device,
  input         io_in_1_bits_memAttr_ewa,
  input         io_in_1_bits_snpAttr,
  input  [7:0]  io_in_1_bits_lpIDWithPadding,
  input         io_in_1_bits_snoopMe,
  input         io_in_1_bits_expCompAck,
  input  [1:0]  io_in_1_bits_tagOp,
  input         io_in_1_bits_traceTag,
  input         io_in_1_bits_mpam_perfMonGroup,
  input  [8:0]  io_in_1_bits_mpam_partID,
  input         io_in_1_bits_mpam_mpamNS,
  input  [3:0]  io_in_1_bits_rsvdc,
  input         io_out_ready,
  output        io_out_valid,
  output [3:0]  io_out_bits_qos,
  output [11:0] io_out_bits_txnID,
  output [10:0] io_out_bits_returnNID,
  output        io_out_bits_stashNIDValid,
  output [11:0] io_out_bits_returnTxnID,
  output [6:0]  io_out_bits_opcode,
  output [2:0]  io_out_bits_size,
  output [47:0] io_out_bits_addr,
  output        io_out_bits_ns,
  output        io_out_bits_likelyshared,
  output        io_out_bits_allowRetry,
  output [1:0]  io_out_bits_order,
  output [3:0]  io_out_bits_pCrdType,
  output        io_out_bits_memAttr_allocate,
  output        io_out_bits_memAttr_cacheable,
  output        io_out_bits_memAttr_device,
  output        io_out_bits_memAttr_ewa,
  output        io_out_bits_snpAttr,
  output [7:0]  io_out_bits_lpIDWithPadding,
  output        io_out_bits_snoopMe,
  output        io_out_bits_expCompAck,
  output [1:0]  io_out_bits_tagOp,
  output        io_out_bits_traceTag,
  output        io_out_bits_mpam_perfMonGroup,
  output [8:0]  io_out_bits_mpam_partID,
  output        io_out_bits_mpam_mpamNS,
  output [3:0]  io_out_bits_rsvdc,
  output [1:0]  io_chosenOH
);

  wire [1:0] chosenOH;
  wire [1:0] valids = {io_in_1_valid, io_in_0_valid};
  reg  [1:0] pendingMask;
  reg  [1:0] rrGrantMask;
  wire       _rrSelOH_oh_WIRE_0 = rrGrantMask[0] & pendingMask[0];
  wire [1:0] rrSelOH =
    {rrGrantMask[1] & pendingMask[1] & ~_rrSelOH_oh_WIRE_0, _rrSelOH_oh_WIRE_0};
  assign chosenOH =
    (|(rrSelOH & valids)) ? rrSelOH : {io_in_1_valid & ~io_in_0_valid, io_in_0_valid};
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      pendingMask <= 2'h0;
      rrGrantMask <= 2'h0;
    end
    else if (io_out_ready & (|valids)) begin
      pendingMask <= valids & ~chosenOH;
      rrGrantMask <= {chosenOH[0], 1'h0};
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        pendingMask = _RANDOM[/*Zero width*/ 1'b0][1:0];
        rrGrantMask = _RANDOM[/*Zero width*/ 1'b0][3:2];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        pendingMask = 2'h0;
        rrGrantMask = 2'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_0_ready = chosenOH[0] & io_out_ready;
  assign io_in_1_ready = chosenOH[1] & io_out_ready;
  assign io_out_valid = |valids;
  assign io_out_bits_qos =
    (chosenOH[0] ? io_in_0_bits_qos : 4'h0) | (chosenOH[1] ? io_in_1_bits_qos : 4'h0);
  assign io_out_bits_txnID =
    (chosenOH[0] ? io_in_0_bits_txnID : 12'h0)
    | (chosenOH[1] ? io_in_1_bits_txnID : 12'h0);
  assign io_out_bits_returnNID =
    (chosenOH[0] ? io_in_0_bits_returnNID : 11'h0)
    | (chosenOH[1] ? io_in_1_bits_returnNID : 11'h0);
  assign io_out_bits_stashNIDValid =
    chosenOH[0] & io_in_0_bits_stashNIDValid | chosenOH[1] & io_in_1_bits_stashNIDValid;
  assign io_out_bits_returnTxnID =
    (chosenOH[0] ? io_in_0_bits_returnTxnID : 12'h0)
    | (chosenOH[1] ? io_in_1_bits_returnTxnID : 12'h0);
  assign io_out_bits_opcode =
    (chosenOH[0] ? io_in_0_bits_opcode : 7'h0)
    | (chosenOH[1] ? io_in_1_bits_opcode : 7'h0);
  assign io_out_bits_size = (|chosenOH) ? 3'h6 : 3'h0;
  assign io_out_bits_addr =
    (chosenOH[0] ? io_in_0_bits_addr : 48'h0) | (chosenOH[1] ? io_in_1_bits_addr : 48'h0);
  assign io_out_bits_ns = chosenOH[0] & io_in_0_bits_ns | chosenOH[1] & io_in_1_bits_ns;
  assign io_out_bits_likelyshared =
    chosenOH[0] & io_in_0_bits_likelyshared | chosenOH[1] & io_in_1_bits_likelyshared;
  assign io_out_bits_allowRetry =
    chosenOH[0] & io_in_0_bits_allowRetry | chosenOH[1] & io_in_1_bits_allowRetry;
  assign io_out_bits_order =
    (chosenOH[0] ? io_in_0_bits_order : 2'h0) | (chosenOH[1] ? io_in_1_bits_order : 2'h0);
  assign io_out_bits_pCrdType =
    (chosenOH[0] ? io_in_0_bits_pCrdType : 4'h0)
    | (chosenOH[1] ? io_in_1_bits_pCrdType : 4'h0);
  assign io_out_bits_memAttr_allocate =
    chosenOH[0] & io_in_0_bits_memAttr_allocate | chosenOH[1]
    & io_in_1_bits_memAttr_allocate;
  assign io_out_bits_memAttr_cacheable =
    chosenOH[0] & io_in_0_bits_memAttr_cacheable | chosenOH[1]
    & io_in_1_bits_memAttr_cacheable;
  assign io_out_bits_memAttr_device =
    chosenOH[0] & io_in_0_bits_memAttr_device | chosenOH[1] & io_in_1_bits_memAttr_device;
  assign io_out_bits_memAttr_ewa =
    chosenOH[0] & io_in_0_bits_memAttr_ewa | chosenOH[1] & io_in_1_bits_memAttr_ewa;
  assign io_out_bits_snpAttr =
    chosenOH[0] & io_in_0_bits_snpAttr | chosenOH[1] & io_in_1_bits_snpAttr;
  assign io_out_bits_lpIDWithPadding =
    (chosenOH[0] ? io_in_0_bits_lpIDWithPadding : 8'h0)
    | (chosenOH[1] ? io_in_1_bits_lpIDWithPadding : 8'h0);
  assign io_out_bits_snoopMe =
    chosenOH[0] & io_in_0_bits_snoopMe | chosenOH[1] & io_in_1_bits_snoopMe;
  assign io_out_bits_expCompAck =
    chosenOH[0] & io_in_0_bits_expCompAck | chosenOH[1] & io_in_1_bits_expCompAck;
  assign io_out_bits_tagOp =
    (chosenOH[0] ? io_in_0_bits_tagOp : 2'h0) | (chosenOH[1] ? io_in_1_bits_tagOp : 2'h0);
  assign io_out_bits_traceTag =
    chosenOH[0] & io_in_0_bits_traceTag | chosenOH[1] & io_in_1_bits_traceTag;
  assign io_out_bits_mpam_perfMonGroup =
    chosenOH[0] & io_in_0_bits_mpam_perfMonGroup | chosenOH[1]
    & io_in_1_bits_mpam_perfMonGroup;
  assign io_out_bits_mpam_partID =
    (chosenOH[0] ? io_in_0_bits_mpam_partID : 9'h0)
    | (chosenOH[1] ? io_in_1_bits_mpam_partID : 9'h0);
  assign io_out_bits_mpam_mpamNS =
    chosenOH[0] & io_in_0_bits_mpam_mpamNS | chosenOH[1] & io_in_1_bits_mpam_mpamNS;
  assign io_out_bits_rsvdc =
    (chosenOH[0] ? io_in_0_bits_rsvdc : 4'h0) | (chosenOH[1] ? io_in_1_bits_rsvdc : 4'h0);
  assign io_chosenOH = chosenOH;
endmodule

