// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module FastArbiter_66(
  input         clock,
  input         reset,
  output        io_in_0_ready,
  input         io_in_0_valid,
  input  [3:0]  io_in_0_bits_qos,
  input  [10:0] io_in_0_bits_tgtID,
  input  [11:0] io_in_0_bits_txnID,
  input  [4:0]  io_in_0_bits_opcode,
  input  [1:0]  io_in_0_bits_respErr,
  input  [2:0]  io_in_0_bits_resp,
  input  [2:0]  io_in_0_bits_fwdState,
  input  [2:0]  io_in_0_bits_cBusy,
  input  [11:0] io_in_0_bits_dbID,
  input  [3:0]  io_in_0_bits_pCrdType,
  input  [1:0]  io_in_0_bits_tagOp,
  input         io_in_0_bits_traceTag,
  output        io_in_1_ready,
  input         io_in_1_valid,
  input  [3:0]  io_in_1_bits_qos,
  input  [10:0] io_in_1_bits_tgtID,
  input  [11:0] io_in_1_bits_txnID,
  input  [4:0]  io_in_1_bits_opcode,
  input  [1:0]  io_in_1_bits_respErr,
  input  [2:0]  io_in_1_bits_resp,
  input  [2:0]  io_in_1_bits_fwdState,
  input  [2:0]  io_in_1_bits_cBusy,
  input  [11:0] io_in_1_bits_dbID,
  input  [3:0]  io_in_1_bits_pCrdType,
  input  [1:0]  io_in_1_bits_tagOp,
  input         io_in_1_bits_traceTag,
  output        io_in_2_ready,
  input         io_in_2_valid,
  input  [3:0]  io_in_2_bits_qos,
  input  [10:0] io_in_2_bits_tgtID,
  input  [11:0] io_in_2_bits_txnID,
  input  [4:0]  io_in_2_bits_opcode,
  input  [1:0]  io_in_2_bits_respErr,
  input  [2:0]  io_in_2_bits_resp,
  input  [2:0]  io_in_2_bits_fwdState,
  input  [2:0]  io_in_2_bits_cBusy,
  input  [11:0] io_in_2_bits_dbID,
  input  [3:0]  io_in_2_bits_pCrdType,
  input  [1:0]  io_in_2_bits_tagOp,
  input         io_in_2_bits_traceTag,
  output        io_in_3_ready,
  input         io_in_3_valid,
  input  [3:0]  io_in_3_bits_qos,
  input  [10:0] io_in_3_bits_tgtID,
  input  [11:0] io_in_3_bits_txnID,
  input  [4:0]  io_in_3_bits_opcode,
  input  [1:0]  io_in_3_bits_respErr,
  input  [2:0]  io_in_3_bits_resp,
  input  [2:0]  io_in_3_bits_fwdState,
  input  [2:0]  io_in_3_bits_cBusy,
  input  [11:0] io_in_3_bits_dbID,
  input  [3:0]  io_in_3_bits_pCrdType,
  input  [1:0]  io_in_3_bits_tagOp,
  input         io_in_3_bits_traceTag,
  input         io_out_ready,
  output        io_out_valid,
  output [3:0]  io_out_bits_qos,
  output [10:0] io_out_bits_tgtID,
  output [11:0] io_out_bits_txnID,
  output [4:0]  io_out_bits_opcode,
  output [1:0]  io_out_bits_respErr,
  output [2:0]  io_out_bits_resp,
  output [2:0]  io_out_bits_fwdState,
  output [2:0]  io_out_bits_cBusy,
  output [11:0] io_out_bits_dbID,
  output [3:0]  io_out_bits_pCrdType,
  output [1:0]  io_out_bits_tagOp,
  output        io_out_bits_traceTag,
  output [1:0]  io_chosen
);

  wire [3:0] chosenOH;
  wire [3:0] valids = {io_in_3_valid, io_in_2_valid, io_in_1_valid, io_in_0_valid};
  reg  [3:0] pendingMask;
  reg  [3:0] rrGrantMask;
  wire       _rrSelOH_oh_WIRE_0 = rrGrantMask[0] & pendingMask[0];
  wire       _rrSelOH_T_2 = rrGrantMask[1] & pendingMask[1];
  wire       _rrSelOH_T_3 = rrGrantMask[2] & pendingMask[2];
  wire [3:0] rrSelOH =
    {rrGrantMask[3] & pendingMask[3]
       & {_rrSelOH_oh_WIRE_0, _rrSelOH_T_2, _rrSelOH_T_3} == 3'h0,
     _rrSelOH_T_3 & {_rrSelOH_oh_WIRE_0, _rrSelOH_T_2} == 2'h0,
     _rrSelOH_T_2 & ~_rrSelOH_oh_WIRE_0,
     _rrSelOH_oh_WIRE_0};
  assign chosenOH =
    (|(rrSelOH & valids))
      ? rrSelOH
      : {io_in_3_valid & {io_in_0_valid, io_in_1_valid, io_in_2_valid} == 3'h0,
         io_in_2_valid & {io_in_0_valid, io_in_1_valid} == 2'h0,
         io_in_1_valid & ~io_in_0_valid,
         io_in_0_valid};
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      pendingMask <= 4'h0;
      rrGrantMask <= 4'h0;
    end
    else if (io_out_ready & (|valids)) begin
      pendingMask <= valids & ~chosenOH;
      rrGrantMask <= {|(chosenOH[2:0]), |(chosenOH[1:0]), chosenOH[0], 1'h0};
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        pendingMask = _RANDOM[/*Zero width*/ 1'b0][3:0];
        rrGrantMask = _RANDOM[/*Zero width*/ 1'b0][7:4];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        pendingMask = 4'h0;
        rrGrantMask = 4'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_0_ready = chosenOH[0] & io_out_ready;
  assign io_in_1_ready = chosenOH[1] & io_out_ready;
  assign io_in_2_ready = chosenOH[2] & io_out_ready;
  assign io_in_3_ready = chosenOH[3] & io_out_ready;
  assign io_out_valid = |valids;
  assign io_out_bits_qos =
    (chosenOH[0] ? io_in_0_bits_qos : 4'h0) | (chosenOH[1] ? io_in_1_bits_qos : 4'h0)
    | (chosenOH[2] ? io_in_2_bits_qos : 4'h0) | (chosenOH[3] ? io_in_3_bits_qos : 4'h0);
  assign io_out_bits_tgtID =
    (chosenOH[0] ? io_in_0_bits_tgtID : 11'h0)
    | (chosenOH[1] ? io_in_1_bits_tgtID : 11'h0)
    | (chosenOH[2] ? io_in_2_bits_tgtID : 11'h0)
    | (chosenOH[3] ? io_in_3_bits_tgtID : 11'h0);
  assign io_out_bits_txnID =
    (chosenOH[0] ? io_in_0_bits_txnID : 12'h0)
    | (chosenOH[1] ? io_in_1_bits_txnID : 12'h0)
    | (chosenOH[2] ? io_in_2_bits_txnID : 12'h0)
    | (chosenOH[3] ? io_in_3_bits_txnID : 12'h0);
  assign io_out_bits_opcode =
    (chosenOH[0] ? io_in_0_bits_opcode : 5'h0)
    | (chosenOH[1] ? io_in_1_bits_opcode : 5'h0)
    | (chosenOH[2] ? io_in_2_bits_opcode : 5'h0)
    | (chosenOH[3] ? io_in_3_bits_opcode : 5'h0);
  assign io_out_bits_respErr =
    (chosenOH[0] ? io_in_0_bits_respErr : 2'h0)
    | (chosenOH[1] ? io_in_1_bits_respErr : 2'h0)
    | (chosenOH[2] ? io_in_2_bits_respErr : 2'h0)
    | (chosenOH[3] ? io_in_3_bits_respErr : 2'h0);
  assign io_out_bits_resp =
    (chosenOH[0] ? io_in_0_bits_resp : 3'h0) | (chosenOH[1] ? io_in_1_bits_resp : 3'h0)
    | (chosenOH[2] ? io_in_2_bits_resp : 3'h0) | (chosenOH[3] ? io_in_3_bits_resp : 3'h0);
  assign io_out_bits_fwdState =
    (chosenOH[0] ? io_in_0_bits_fwdState : 3'h0)
    | (chosenOH[1] ? io_in_1_bits_fwdState : 3'h0)
    | (chosenOH[2] ? io_in_2_bits_fwdState : 3'h0)
    | (chosenOH[3] ? io_in_3_bits_fwdState : 3'h0);
  assign io_out_bits_cBusy =
    (chosenOH[0] ? io_in_0_bits_cBusy : 3'h0) | (chosenOH[1] ? io_in_1_bits_cBusy : 3'h0)
    | (chosenOH[2] ? io_in_2_bits_cBusy : 3'h0)
    | (chosenOH[3] ? io_in_3_bits_cBusy : 3'h0);
  assign io_out_bits_dbID =
    (chosenOH[0] ? io_in_0_bits_dbID : 12'h0) | (chosenOH[1] ? io_in_1_bits_dbID : 12'h0)
    | (chosenOH[2] ? io_in_2_bits_dbID : 12'h0)
    | (chosenOH[3] ? io_in_3_bits_dbID : 12'h0);
  assign io_out_bits_pCrdType =
    (chosenOH[0] ? io_in_0_bits_pCrdType : 4'h0)
    | (chosenOH[1] ? io_in_1_bits_pCrdType : 4'h0)
    | (chosenOH[2] ? io_in_2_bits_pCrdType : 4'h0)
    | (chosenOH[3] ? io_in_3_bits_pCrdType : 4'h0);
  assign io_out_bits_tagOp =
    (chosenOH[0] ? io_in_0_bits_tagOp : 2'h0) | (chosenOH[1] ? io_in_1_bits_tagOp : 2'h0)
    | (chosenOH[2] ? io_in_2_bits_tagOp : 2'h0)
    | (chosenOH[3] ? io_in_3_bits_tagOp : 2'h0);
  assign io_out_bits_traceTag =
    chosenOH[0] & io_in_0_bits_traceTag | chosenOH[1] & io_in_1_bits_traceTag
    | chosenOH[2] & io_in_2_bits_traceTag | chosenOH[3] & io_in_3_bits_traceTag;
  assign io_chosen = {|(chosenOH[3:2]), chosenOH[3] | chosenOH[1]};
endmodule

