// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module L2Cache(
  input          clock,
  input          reset,
  input  [5:0]   mbist_array,
  input          mbist_all,
  input          mbist_req,
  output         mbist_ack,
  input          mbist_writeen,
  input  [7:0]   mbist_be,
  input  [13:0]  mbist_addr,
  input  [147:0] mbist_indata,
  input          mbist_readen,
  input  [13:0]  mbist_addr_rd,
  output [147:0] mbist_outdata,
  output         toNextPipeline_0_array,
  output         toNextPipeline_0_all,
  output         toNextPipeline_0_req,
  input          toNextPipeline_0_ack,
  output         toNextPipeline_0_writeen,
  output         toNextPipeline_0_be,
  output [8:0]   toNextPipeline_0_addr,
  output [12:0]  toNextPipeline_0_indata,
  output         toNextPipeline_0_readen,
  output [8:0]   toNextPipeline_0_addr_rd,
  input  [12:0]  toNextPipeline_0_outdata,
  output [3:0]   toNextPipeline_1_array,
  output         toNextPipeline_1_all,
  output         toNextPipeline_1_req,
  input          toNextPipeline_1_ack,
  output         toNextPipeline_1_writeen,
  output [7:0]   toNextPipeline_1_be,
  output [13:0]  toNextPipeline_1_addr,
  output [147:0] toNextPipeline_1_indata,
  output         toNextPipeline_1_readen,
  output [13:0]  toNextPipeline_1_addr_rd,
  input  [147:0] toNextPipeline_1_outdata,
  output [4:0]   toNextPipeline_2_array,
  output         toNextPipeline_2_all,
  output         toNextPipeline_2_req,
  input          toNextPipeline_2_ack,
  output         toNextPipeline_2_writeen,
  output [7:0]   toNextPipeline_2_be,
  output [13:0]  toNextPipeline_2_addr,
  output [147:0] toNextPipeline_2_indata,
  output         toNextPipeline_2_readen,
  output [13:0]  toNextPipeline_2_addr_rd,
  input  [147:0] toNextPipeline_2_outdata,
  output [4:0]   toNextPipeline_3_array,
  output         toNextPipeline_3_all,
  output         toNextPipeline_3_req,
  input          toNextPipeline_3_ack,
  output         toNextPipeline_3_writeen,
  output [7:0]   toNextPipeline_3_be,
  output [13:0]  toNextPipeline_3_addr,
  output [147:0] toNextPipeline_3_indata,
  output         toNextPipeline_3_readen,
  output [13:0]  toNextPipeline_3_addr_rd,
  input  [147:0] toNextPipeline_3_outdata,
  output [5:0]   toNextPipeline_4_array,
  output         toNextPipeline_4_all,
  output         toNextPipeline_4_req,
  input          toNextPipeline_4_ack,
  output         toNextPipeline_4_writeen,
  output [7:0]   toNextPipeline_4_be,
  output [13:0]  toNextPipeline_4_addr,
  output [147:0] toNextPipeline_4_indata,
  output         toNextPipeline_4_readen,
  output [13:0]  toNextPipeline_4_addr_rd,
  input  [147:0] toNextPipeline_4_outdata
);

  wire         activated =
    mbist_all | mbist_req
    & (mbist_array == 6'h0 | mbist_array == 6'h1 | mbist_array == 6'h2
       | mbist_array == 6'h3 | mbist_array == 6'h4 | mbist_array == 6'h5
       | mbist_array == 6'h6 | mbist_array == 6'h7 | mbist_array == 6'h8
       | mbist_array == 6'h9 | mbist_array == 6'hA | mbist_array == 6'hB
       | mbist_array == 6'hC | mbist_array == 6'hD | mbist_array == 6'hE
       | mbist_array == 6'hF | mbist_array == 6'h10 | mbist_array == 6'h11
       | mbist_array == 6'h12 | mbist_array == 6'h13 | mbist_array == 6'h14
       | mbist_array == 6'h15 | mbist_array == 6'h16 | mbist_array == 6'h17
       | mbist_array == 6'h18 | mbist_array == 6'h19 | mbist_array == 6'h1A
       | mbist_array == 6'h1B | mbist_array == 6'h1C | mbist_array == 6'h1D
       | mbist_array == 6'h1E | mbist_array == 6'h1F | mbist_array == 6'h20
       | mbist_array == 6'h21 | mbist_array == 6'h22 | mbist_array == 6'h23
       | mbist_array == 6'h24 | mbist_array == 6'h25);
  reg  [5:0]   arrayReg;
  reg          reqReg;
  reg          allReg;
  reg          wenReg;
  reg  [7:0]   beReg;
  reg  [13:0]  addrReg;
  reg  [147:0] dataInReg;
  reg          renReg;
  reg  [13:0]  addrRdReg;
  reg  [147:0] pipelineDataOutReg;
  wire         selected = arrayReg == 6'h0 | arrayReg == 6'h1;
  wire         doSpread = selected | allReg;
  wire         selected_1 =
    arrayReg == 6'h2 | arrayReg == 6'h3 | arrayReg == 6'h4 | arrayReg == 6'h5
    | arrayReg == 6'h6 | arrayReg == 6'h7 | arrayReg == 6'h8 | arrayReg == 6'h9
    | arrayReg == 6'hA;
  wire         doSpread_1 = selected_1 | allReg;
  wire         selected_2 =
    arrayReg == 6'hB | arrayReg == 6'hC | arrayReg == 6'hD | arrayReg == 6'hE
    | arrayReg == 6'hF | arrayReg == 6'h10 | arrayReg == 6'h11 | arrayReg == 6'h12
    | arrayReg == 6'h13;
  wire         doSpread_2 = selected_2 | allReg;
  wire         selected_3 =
    arrayReg == 6'h14 | arrayReg == 6'h15 | arrayReg == 6'h16 | arrayReg == 6'h17
    | arrayReg == 6'h18 | arrayReg == 6'h19 | arrayReg == 6'h1A | arrayReg == 6'h1B
    | arrayReg == 6'h1C;
  wire         doSpread_3 = selected_3 | allReg;
  wire         selected_4 =
    arrayReg == 6'h1D | arrayReg == 6'h1E | arrayReg == 6'h1F | arrayReg == 6'h20
    | arrayReg == 6'h21 | arrayReg == 6'h22 | arrayReg == 6'h23 | arrayReg == 6'h24
    | arrayReg == 6'h25;
  wire         doSpread_4 = selected_4 | allReg;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      arrayReg <= 6'h0;
      reqReg <= 1'h0;
      allReg <= 1'h0;
      wenReg <= 1'h0;
      beReg <= 8'h0;
      addrReg <= 14'h0;
      dataInReg <= 148'h0;
      renReg <= 1'h0;
      addrRdReg <= 14'h0;
    end
    else begin
      if (activated) begin
        arrayReg <= mbist_array;
        allReg <= mbist_all;
        wenReg <= mbist_writeen;
        renReg <= mbist_readen;
      end
      reqReg <= mbist_req;
      if (activated & (mbist_readen | mbist_writeen)) begin
        beReg <= mbist_be;
        addrReg <= mbist_addr;
        dataInReg <= mbist_indata;
        addrRdReg <= mbist_addr_rd;
      end
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (activated)
      pipelineDataOutReg <=
        {135'h0, selected ? toNextPipeline_0_outdata : 13'h0}
        | (selected_1 ? toNextPipeline_1_outdata : 148'h0)
        | (selected_2 ? toNextPipeline_2_outdata : 148'h0)
        | (selected_3 ? toNextPipeline_3_outdata : 148'h0)
        | (selected_4 ? toNextPipeline_4_outdata : 148'h0);
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:10];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'hB; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        arrayReg = _RANDOM[4'h0][5:0];
        reqReg = _RANDOM[4'h0][6];
        allReg = _RANDOM[4'h0][7];
        wenReg = _RANDOM[4'h0][8];
        beReg = _RANDOM[4'h0][16:9];
        addrReg = _RANDOM[4'h0][30:17];
        dataInReg =
          {_RANDOM[4'h0][31],
           _RANDOM[4'h1],
           _RANDOM[4'h2],
           _RANDOM[4'h3],
           _RANDOM[4'h4],
           _RANDOM[4'h5][18:0]};
        renReg = _RANDOM[4'h5][19];
        addrRdReg = {_RANDOM[4'h5][31:20], _RANDOM[4'h6][1:0]};
        pipelineDataOutReg =
          {_RANDOM[4'h6][31:2],
           _RANDOM[4'h7],
           _RANDOM[4'h8],
           _RANDOM[4'h9],
           _RANDOM[4'hA][21:0]};
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        arrayReg = 6'h0;
        reqReg = 1'h0;
        allReg = 1'h0;
        wenReg = 1'h0;
        beReg = 8'h0;
        addrReg = 14'h0;
        dataInReg = 148'h0;
        renReg = 1'h0;
        addrRdReg = 14'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign mbist_ack =
    reqReg
    & (toNextPipeline_0_ack | toNextPipeline_1_ack | toNextPipeline_2_ack
       | toNextPipeline_3_ack | toNextPipeline_4_ack);
  assign mbist_outdata = pipelineDataOutReg;
  assign toNextPipeline_0_array = doSpread & arrayReg[0];
  assign toNextPipeline_0_all = doSpread & allReg;
  assign toNextPipeline_0_req = reqReg;
  assign toNextPipeline_0_writeen = doSpread & wenReg;
  assign toNextPipeline_0_be = beReg[0];
  assign toNextPipeline_0_addr = doSpread ? addrReg[8:0] : 9'h0;
  assign toNextPipeline_0_indata = dataInReg[12:0];
  assign toNextPipeline_0_readen = doSpread & renReg;
  assign toNextPipeline_0_addr_rd = doSpread ? addrRdReg[8:0] : 9'h0;
  assign toNextPipeline_1_array = doSpread_1 ? arrayReg[3:0] : 4'h0;
  assign toNextPipeline_1_all = doSpread_1 & allReg;
  assign toNextPipeline_1_req = reqReg;
  assign toNextPipeline_1_writeen = doSpread_1 & wenReg;
  assign toNextPipeline_1_be = beReg;
  assign toNextPipeline_1_addr = doSpread_1 ? addrReg : 14'h0;
  assign toNextPipeline_1_indata = dataInReg;
  assign toNextPipeline_1_readen = doSpread_1 & renReg;
  assign toNextPipeline_1_addr_rd = doSpread_1 ? addrRdReg : 14'h0;
  assign toNextPipeline_2_array = doSpread_2 ? arrayReg[4:0] : 5'h0;
  assign toNextPipeline_2_all = doSpread_2 & allReg;
  assign toNextPipeline_2_req = reqReg;
  assign toNextPipeline_2_writeen = doSpread_2 & wenReg;
  assign toNextPipeline_2_be = beReg;
  assign toNextPipeline_2_addr = doSpread_2 ? addrReg : 14'h0;
  assign toNextPipeline_2_indata = dataInReg;
  assign toNextPipeline_2_readen = doSpread_2 & renReg;
  assign toNextPipeline_2_addr_rd = doSpread_2 ? addrRdReg : 14'h0;
  assign toNextPipeline_3_array = doSpread_3 ? arrayReg[4:0] : 5'h0;
  assign toNextPipeline_3_all = doSpread_3 & allReg;
  assign toNextPipeline_3_req = reqReg;
  assign toNextPipeline_3_writeen = doSpread_3 & wenReg;
  assign toNextPipeline_3_be = beReg;
  assign toNextPipeline_3_addr = doSpread_3 ? addrReg : 14'h0;
  assign toNextPipeline_3_indata = dataInReg;
  assign toNextPipeline_3_readen = doSpread_3 & renReg;
  assign toNextPipeline_3_addr_rd = doSpread_3 ? addrRdReg : 14'h0;
  assign toNextPipeline_4_array = doSpread_4 ? arrayReg : 6'h0;
  assign toNextPipeline_4_all = doSpread_4 & allReg;
  assign toNextPipeline_4_req = reqReg;
  assign toNextPipeline_4_writeen = doSpread_4 & wenReg;
  assign toNextPipeline_4_be = beReg;
  assign toNextPipeline_4_addr = doSpread_4 ? addrReg : 14'h0;
  assign toNextPipeline_4_indata = dataInReg;
  assign toNextPipeline_4_readen = doSpread_4 & renReg;
  assign toNextPipeline_4_addr_rd = doSpread_4 ? addrRdReg : 14'h0;
endmodule

