// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module L2Slice_3(
  input          clock,
  input          reset,
  input  [5:0]   mbist_array,
  input          mbist_all,
  input          mbist_req,
  output         mbist_ack,
  input          mbist_writeen,
  input  [7:0]   mbist_be,
  input  [13:0]  mbist_addr,
  input  [147:0] mbist_indata,
  input          mbist_readen,
  input  [13:0]  mbist_addr_rd,
  output [147:0] mbist_outdata,
  output [5:0]   toNextPipeline_0_array,
  output         toNextPipeline_0_all,
  output         toNextPipeline_0_req,
  input          toNextPipeline_0_ack,
  output         toNextPipeline_0_writeen,
  output [7:0]   toNextPipeline_0_be,
  output [10:0]  toNextPipeline_0_addr,
  output [147:0] toNextPipeline_0_indata,
  output         toNextPipeline_0_readen,
  output [10:0]  toNextPipeline_0_addr_rd,
  input  [147:0] toNextPipeline_0_outdata,
  output [5:0]   toNextPipeline_1_array,
  output         toNextPipeline_1_all,
  output         toNextPipeline_1_req,
  input          toNextPipeline_1_ack,
  output         toNextPipeline_1_writeen,
  output         toNextPipeline_1_be,
  output [13:0]  toNextPipeline_1_addr,
  output [136:0] toNextPipeline_1_indata,
  output         toNextPipeline_1_readen,
  output [13:0]  toNextPipeline_1_addr_rd,
  input  [136:0] toNextPipeline_1_outdata
);

  wire         activated =
    mbist_all | mbist_req
    & (mbist_array == 6'h1D | mbist_array == 6'h1E | mbist_array == 6'h1F
       | mbist_array == 6'h20 | mbist_array == 6'h21 | mbist_array == 6'h22
       | mbist_array == 6'h23 | mbist_array == 6'h24 | mbist_array == 6'h25);
  reg  [5:0]   arrayReg;
  reg          reqReg;
  reg          allReg;
  reg          wenReg;
  reg  [7:0]   beReg;
  reg  [13:0]  addrReg;
  reg  [147:0] dataInReg;
  reg          renReg;
  reg  [13:0]  addrRdReg;
  reg  [147:0] pipelineDataOutReg;
  wire         selected =
    arrayReg == 6'h1D | arrayReg == 6'h1E | arrayReg == 6'h1F | arrayReg == 6'h20
    | arrayReg == 6'h21;
  wire         doSpread = selected | allReg;
  wire         selected_1 =
    arrayReg == 6'h22 | arrayReg == 6'h23 | arrayReg == 6'h24 | arrayReg == 6'h25;
  wire         doSpread_1 = selected_1 | allReg;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      arrayReg <= 6'h0;
      reqReg <= 1'h0;
      allReg <= 1'h0;
      wenReg <= 1'h0;
      beReg <= 8'h0;
      addrReg <= 14'h0;
      dataInReg <= 148'h0;
      renReg <= 1'h0;
      addrRdReg <= 14'h0;
    end
    else begin
      if (activated) begin
        arrayReg <= mbist_array;
        allReg <= mbist_all;
        wenReg <= mbist_writeen;
        renReg <= mbist_readen;
      end
      reqReg <= mbist_req;
      if (activated & (mbist_readen | mbist_writeen)) begin
        beReg <= mbist_be;
        addrReg <= mbist_addr;
        dataInReg <= mbist_indata;
        addrRdReg <= mbist_addr_rd;
      end
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (activated)
      pipelineDataOutReg <=
        (selected ? toNextPipeline_0_outdata : 148'h0)
        | {11'h0, selected_1 ? toNextPipeline_1_outdata : 137'h0};
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:10];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'hB; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        arrayReg = _RANDOM[4'h0][5:0];
        reqReg = _RANDOM[4'h0][6];
        allReg = _RANDOM[4'h0][7];
        wenReg = _RANDOM[4'h0][8];
        beReg = _RANDOM[4'h0][16:9];
        addrReg = _RANDOM[4'h0][30:17];
        dataInReg =
          {_RANDOM[4'h0][31],
           _RANDOM[4'h1],
           _RANDOM[4'h2],
           _RANDOM[4'h3],
           _RANDOM[4'h4],
           _RANDOM[4'h5][18:0]};
        renReg = _RANDOM[4'h5][19];
        addrRdReg = {_RANDOM[4'h5][31:20], _RANDOM[4'h6][1:0]};
        pipelineDataOutReg =
          {_RANDOM[4'h6][31:2],
           _RANDOM[4'h7],
           _RANDOM[4'h8],
           _RANDOM[4'h9],
           _RANDOM[4'hA][21:0]};
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        arrayReg = 6'h0;
        reqReg = 1'h0;
        allReg = 1'h0;
        wenReg = 1'h0;
        beReg = 8'h0;
        addrReg = 14'h0;
        dataInReg = 148'h0;
        renReg = 1'h0;
        addrRdReg = 14'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign mbist_ack = reqReg & (toNextPipeline_0_ack | toNextPipeline_1_ack);
  assign mbist_outdata = pipelineDataOutReg;
  assign toNextPipeline_0_array = doSpread ? arrayReg : 6'h0;
  assign toNextPipeline_0_all = doSpread & allReg;
  assign toNextPipeline_0_req = reqReg;
  assign toNextPipeline_0_writeen = doSpread & wenReg;
  assign toNextPipeline_0_be = beReg;
  assign toNextPipeline_0_addr = doSpread ? addrReg[10:0] : 11'h0;
  assign toNextPipeline_0_indata = dataInReg;
  assign toNextPipeline_0_readen = doSpread & renReg;
  assign toNextPipeline_0_addr_rd = doSpread ? addrRdReg[10:0] : 11'h0;
  assign toNextPipeline_1_array = doSpread_1 ? arrayReg : 6'h0;
  assign toNextPipeline_1_all = doSpread_1 & allReg;
  assign toNextPipeline_1_req = reqReg;
  assign toNextPipeline_1_writeen = doSpread_1 & wenReg;
  assign toNextPipeline_1_be = beReg[0];
  assign toNextPipeline_1_addr = doSpread_1 ? addrReg : 14'h0;
  assign toNextPipeline_1_indata = dataInReg[136:0];
  assign toNextPipeline_1_readen = doSpread_1 & renReg;
  assign toNextPipeline_1_addr_rd = doSpread_1 ? addrRdReg : 14'h0;
endmodule

