// Generated by CIRCT firtool-1.135.0
module MbistClockGateCell(
  input  clock,
  input  mbist_writeen,
  input  mbist_readen,
  input  mbist_req,
  input  E,
  input  dft_cgen,
  output out_clock
);

  ClockGate CG (
    .TE (dft_cgen),
    .E  (mbist_req ? mbist_readen | mbist_writeen : E),
    .CK (clock),
    .Q  (out_clock)
  );
endmodule

