// Generated by CIRCT firtool-1.135.0
module PrefetchReceiver(
  output        io_req_valid,
  output [31:0] io_req_bits_tag,
  output [9:0]  io_req_bits_set,
  output [4:0]  io_req_bits_pfSource,
  input         io_recv_addr_valid,
  input  [63:0] io_recv_addr_bits_addr,
  input  [4:0]  io_recv_addr_bits_pfSource,
  input         io_enable
);

  assign io_req_valid = io_enable & io_recv_addr_valid;
  assign io_req_bits_tag = io_recv_addr_bits_addr[47:16];
  assign io_req_bits_set = io_recv_addr_bits_addr[15:6];
  assign io_req_bits_pfSource = io_recv_addr_bits_pfSource;
endmodule

