// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Queue1_ChosenQBundle(
  input         clock,
  input         reset,
  output        io_enq_ready,
  input         io_enq_valid,
  input         io_enq_bits_bits_valid,
  input         io_enq_bits_bits_rdy,
  input  [2:0]  io_enq_bits_bits_task_channel,
  input  [9:0]  io_enq_bits_bits_task_set,
  input  [29:0] io_enq_bits_bits_task_tag,
  input  [5:0]  io_enq_bits_bits_task_off,
  input  [1:0]  io_enq_bits_bits_task_alias,
  input  [43:0] io_enq_bits_bits_task_vaddr,
  input         io_enq_bits_bits_task_isKeyword,
  input  [3:0]  io_enq_bits_bits_task_opcode,
  input  [2:0]  io_enq_bits_bits_task_param,
  input  [2:0]  io_enq_bits_bits_task_size,
  input  [6:0]  io_enq_bits_bits_task_sourceId,
  input         io_enq_bits_bits_task_corrupt,
  input         io_enq_bits_bits_task_fromL2pft,
  input         io_enq_bits_bits_task_needHint,
  input  [4:0]  io_enq_bits_bits_task_reqSource,
  input  [3:0]  io_enq_bits_bits_waitMP,
  input  [15:0] io_enq_bits_bits_waitMS,
  input  [3:0]  io_enq_bits_idOH,
  input         io_deq_ready,
  output        io_deq_valid,
  output [2:0]  io_deq_bits_bits_task_channel,
  output [2:0]  io_deq_bits_bits_task_txChannel,
  output [9:0]  io_deq_bits_bits_task_set,
  output [29:0] io_deq_bits_bits_task_tag,
  output [5:0]  io_deq_bits_bits_task_off,
  output [1:0]  io_deq_bits_bits_task_alias,
  output [43:0] io_deq_bits_bits_task_vaddr,
  output        io_deq_bits_bits_task_isKeyword,
  output [3:0]  io_deq_bits_bits_task_opcode,
  output [2:0]  io_deq_bits_bits_task_param,
  output [2:0]  io_deq_bits_bits_task_size,
  output [6:0]  io_deq_bits_bits_task_sourceId,
  output [1:0]  io_deq_bits_bits_task_bufIdx,
  output        io_deq_bits_bits_task_needProbeAckData,
  output        io_deq_bits_bits_task_denied,
  output        io_deq_bits_bits_task_corrupt,
  output        io_deq_bits_bits_task_mshrTask,
  output [7:0]  io_deq_bits_bits_task_mshrId,
  output        io_deq_bits_bits_task_aliasTask,
  output        io_deq_bits_bits_task_useProbeData,
  output        io_deq_bits_bits_task_mshrRetry,
  output        io_deq_bits_bits_task_readProbeDataDown,
  output        io_deq_bits_bits_task_fromL2pft,
  output        io_deq_bits_bits_task_needHint,
  output        io_deq_bits_bits_task_dirty,
  output [2:0]  io_deq_bits_bits_task_way,
  output        io_deq_bits_bits_task_meta_dirty,
  output [1:0]  io_deq_bits_bits_task_meta_state,
  output        io_deq_bits_bits_task_meta_clients,
  output [1:0]  io_deq_bits_bits_task_meta_alias,
  output        io_deq_bits_bits_task_meta_prefetch,
  output [3:0]  io_deq_bits_bits_task_meta_prefetchSrc,
  output        io_deq_bits_bits_task_meta_accessed,
  output        io_deq_bits_bits_task_meta_tagErr,
  output        io_deq_bits_bits_task_meta_dataErr,
  output        io_deq_bits_bits_task_metaWen,
  output        io_deq_bits_bits_task_tagWen,
  output        io_deq_bits_bits_task_dsWen,
  output        io_deq_bits_bits_task_replTask,
  output        io_deq_bits_bits_task_cmoTask,
  output        io_deq_bits_bits_task_cmoAll,
  output [4:0]  io_deq_bits_bits_task_reqSource,
  output        io_deq_bits_bits_task_mergeA,
  output [5:0]  io_deq_bits_bits_task_aMergeTask_off,
  output [1:0]  io_deq_bits_bits_task_aMergeTask_alias,
  output [43:0] io_deq_bits_bits_task_aMergeTask_vaddr,
  output        io_deq_bits_bits_task_aMergeTask_isKeyword,
  output [2:0]  io_deq_bits_bits_task_aMergeTask_opcode,
  output [2:0]  io_deq_bits_bits_task_aMergeTask_param,
  output [6:0]  io_deq_bits_bits_task_aMergeTask_sourceId,
  output        io_deq_bits_bits_task_aMergeTask_meta_dirty,
  output [1:0]  io_deq_bits_bits_task_aMergeTask_meta_state,
  output        io_deq_bits_bits_task_aMergeTask_meta_clients,
  output [1:0]  io_deq_bits_bits_task_aMergeTask_meta_alias,
  output        io_deq_bits_bits_task_aMergeTask_meta_prefetch,
  output [3:0]  io_deq_bits_bits_task_aMergeTask_meta_prefetchSrc,
  output        io_deq_bits_bits_task_aMergeTask_meta_accessed,
  output        io_deq_bits_bits_task_aMergeTask_meta_tagErr,
  output        io_deq_bits_bits_task_aMergeTask_meta_dataErr,
  output        io_deq_bits_bits_task_snpHitRelease,
  output        io_deq_bits_bits_task_snpHitReleaseToInval,
  output        io_deq_bits_bits_task_snpHitReleaseToClean,
  output        io_deq_bits_bits_task_snpHitReleaseWithData,
  output [7:0]  io_deq_bits_bits_task_snpHitReleaseIdx,
  output        io_deq_bits_bits_task_snpHitReleaseMeta_dirty,
  output [1:0]  io_deq_bits_bits_task_snpHitReleaseMeta_state,
  output        io_deq_bits_bits_task_snpHitReleaseMeta_clients,
  output [1:0]  io_deq_bits_bits_task_snpHitReleaseMeta_alias,
  output        io_deq_bits_bits_task_snpHitReleaseMeta_prefetch,
  output [3:0]  io_deq_bits_bits_task_snpHitReleaseMeta_prefetchSrc,
  output        io_deq_bits_bits_task_snpHitReleaseMeta_accessed,
  output        io_deq_bits_bits_task_snpHitReleaseMeta_tagErr,
  output        io_deq_bits_bits_task_snpHitReleaseMeta_dataErr,
  output [10:0] io_deq_bits_bits_task_tgtID,
  output [10:0] io_deq_bits_bits_task_srcID,
  output [11:0] io_deq_bits_bits_task_txnID,
  output [10:0] io_deq_bits_bits_task_homeNID,
  output [11:0] io_deq_bits_bits_task_dbID,
  output [10:0] io_deq_bits_bits_task_fwdNID,
  output [11:0] io_deq_bits_bits_task_fwdTxnID,
  output [6:0]  io_deq_bits_bits_task_chiOpcode,
  output [2:0]  io_deq_bits_bits_task_resp,
  output [2:0]  io_deq_bits_bits_task_fwdState,
  output [3:0]  io_deq_bits_bits_task_pCrdType,
  output        io_deq_bits_bits_task_retToSrc,
  output        io_deq_bits_bits_task_likelyshared,
  output        io_deq_bits_bits_task_expCompAck,
  output        io_deq_bits_bits_task_allowRetry,
  output        io_deq_bits_bits_task_memAttr_allocate,
  output        io_deq_bits_bits_task_memAttr_cacheable,
  output        io_deq_bits_bits_task_memAttr_device,
  output        io_deq_bits_bits_task_memAttr_ewa,
  output        io_deq_bits_bits_task_traceTag,
  output [3:0]  io_deq_bits_idOH
);

  reg  [411:0] ram;
  wire         io_enq_ready_0;
  reg          maybe_full;
  wire         do_enq = io_enq_ready_0 & io_enq_valid;
  assign io_enq_ready_0 = io_deq_ready | ~maybe_full;
  always @(posedge clock or posedge reset) begin
    if (reset)
      maybe_full <= 1'h0;
    else if (do_enq != (io_deq_ready & maybe_full))
      maybe_full <= do_enq;
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (do_enq)
      ram <=
        {io_enq_bits_bits_valid,
         io_enq_bits_bits_rdy,
         io_enq_bits_bits_task_channel,
         3'h0,
         io_enq_bits_bits_task_set,
         io_enq_bits_bits_task_tag,
         io_enq_bits_bits_task_off,
         io_enq_bits_bits_task_alias,
         io_enq_bits_bits_task_vaddr,
         io_enq_bits_bits_task_isKeyword,
         io_enq_bits_bits_task_opcode,
         io_enq_bits_bits_task_param,
         io_enq_bits_bits_task_size,
         io_enq_bits_bits_task_sourceId,
         4'h0,
         io_enq_bits_bits_task_corrupt,
         13'h0,
         io_enq_bits_bits_task_fromL2pft,
         io_enq_bits_bits_task_needHint,
         32'h0,
         io_enq_bits_bits_task_reqSource,
         213'h0,
         io_enq_bits_bits_waitMP,
         io_enq_bits_bits_waitMS,
         io_enq_bits_idOH};
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:12];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'hD; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        maybe_full = _RANDOM[4'h0][0];
        ram =
          {_RANDOM[4'h0][31:1],
           _RANDOM[4'h1],
           _RANDOM[4'h2],
           _RANDOM[4'h3],
           _RANDOM[4'h4],
           _RANDOM[4'h5],
           _RANDOM[4'h6],
           _RANDOM[4'h7],
           _RANDOM[4'h8],
           _RANDOM[4'h9],
           _RANDOM[4'hA],
           _RANDOM[4'hB],
           _RANDOM[4'hC][28:0]};
      `endif // RANDOMIZE_REG_INIT
      if (reset)
        maybe_full = 1'h0;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_ready = io_enq_ready_0;
  assign io_deq_valid = maybe_full;
  assign io_deq_bits_bits_task_channel = ram[409:407];
  assign io_deq_bits_bits_task_txChannel = ram[406:404];
  assign io_deq_bits_bits_task_set = ram[403:394];
  assign io_deq_bits_bits_task_tag = ram[393:364];
  assign io_deq_bits_bits_task_off = ram[363:358];
  assign io_deq_bits_bits_task_alias = ram[357:356];
  assign io_deq_bits_bits_task_vaddr = ram[355:312];
  assign io_deq_bits_bits_task_isKeyword = ram[311];
  assign io_deq_bits_bits_task_opcode = ram[310:307];
  assign io_deq_bits_bits_task_param = ram[306:304];
  assign io_deq_bits_bits_task_size = ram[303:301];
  assign io_deq_bits_bits_task_sourceId = ram[300:294];
  assign io_deq_bits_bits_task_bufIdx = ram[293:292];
  assign io_deq_bits_bits_task_needProbeAckData = ram[291];
  assign io_deq_bits_bits_task_denied = ram[290];
  assign io_deq_bits_bits_task_corrupt = ram[289];
  assign io_deq_bits_bits_task_mshrTask = ram[288];
  assign io_deq_bits_bits_task_mshrId = ram[287:280];
  assign io_deq_bits_bits_task_aliasTask = ram[279];
  assign io_deq_bits_bits_task_useProbeData = ram[278];
  assign io_deq_bits_bits_task_mshrRetry = ram[277];
  assign io_deq_bits_bits_task_readProbeDataDown = ram[276];
  assign io_deq_bits_bits_task_fromL2pft = ram[275];
  assign io_deq_bits_bits_task_needHint = ram[274];
  assign io_deq_bits_bits_task_dirty = ram[273];
  assign io_deq_bits_bits_task_way = ram[272:270];
  assign io_deq_bits_bits_task_meta_dirty = ram[269];
  assign io_deq_bits_bits_task_meta_state = ram[268:267];
  assign io_deq_bits_bits_task_meta_clients = ram[266];
  assign io_deq_bits_bits_task_meta_alias = ram[265:264];
  assign io_deq_bits_bits_task_meta_prefetch = ram[263];
  assign io_deq_bits_bits_task_meta_prefetchSrc = ram[262:259];
  assign io_deq_bits_bits_task_meta_accessed = ram[258];
  assign io_deq_bits_bits_task_meta_tagErr = ram[257];
  assign io_deq_bits_bits_task_meta_dataErr = ram[256];
  assign io_deq_bits_bits_task_metaWen = ram[255];
  assign io_deq_bits_bits_task_tagWen = ram[254];
  assign io_deq_bits_bits_task_dsWen = ram[253];
  assign io_deq_bits_bits_task_replTask = ram[244];
  assign io_deq_bits_bits_task_cmoTask = ram[243];
  assign io_deq_bits_bits_task_cmoAll = ram[242];
  assign io_deq_bits_bits_task_reqSource = ram[241:237];
  assign io_deq_bits_bits_task_mergeA = ram[236];
  assign io_deq_bits_bits_task_aMergeTask_off = ram[235:230];
  assign io_deq_bits_bits_task_aMergeTask_alias = ram[229:228];
  assign io_deq_bits_bits_task_aMergeTask_vaddr = ram[227:184];
  assign io_deq_bits_bits_task_aMergeTask_isKeyword = ram[183];
  assign io_deq_bits_bits_task_aMergeTask_opcode = ram[182:180];
  assign io_deq_bits_bits_task_aMergeTask_param = ram[179:177];
  assign io_deq_bits_bits_task_aMergeTask_sourceId = ram[176:170];
  assign io_deq_bits_bits_task_aMergeTask_meta_dirty = ram[169];
  assign io_deq_bits_bits_task_aMergeTask_meta_state = ram[168:167];
  assign io_deq_bits_bits_task_aMergeTask_meta_clients = ram[166];
  assign io_deq_bits_bits_task_aMergeTask_meta_alias = ram[165:164];
  assign io_deq_bits_bits_task_aMergeTask_meta_prefetch = ram[163];
  assign io_deq_bits_bits_task_aMergeTask_meta_prefetchSrc = ram[162:159];
  assign io_deq_bits_bits_task_aMergeTask_meta_accessed = ram[158];
  assign io_deq_bits_bits_task_aMergeTask_meta_tagErr = ram[157];
  assign io_deq_bits_bits_task_aMergeTask_meta_dataErr = ram[156];
  assign io_deq_bits_bits_task_snpHitRelease = ram[155];
  assign io_deq_bits_bits_task_snpHitReleaseToInval = ram[154];
  assign io_deq_bits_bits_task_snpHitReleaseToClean = ram[153];
  assign io_deq_bits_bits_task_snpHitReleaseWithData = ram[152];
  assign io_deq_bits_bits_task_snpHitReleaseIdx = ram[151:144];
  assign io_deq_bits_bits_task_snpHitReleaseMeta_dirty = ram[143];
  assign io_deq_bits_bits_task_snpHitReleaseMeta_state = ram[142:141];
  assign io_deq_bits_bits_task_snpHitReleaseMeta_clients = ram[140];
  assign io_deq_bits_bits_task_snpHitReleaseMeta_alias = ram[139:138];
  assign io_deq_bits_bits_task_snpHitReleaseMeta_prefetch = ram[137];
  assign io_deq_bits_bits_task_snpHitReleaseMeta_prefetchSrc = ram[136:133];
  assign io_deq_bits_bits_task_snpHitReleaseMeta_accessed = ram[132];
  assign io_deq_bits_bits_task_snpHitReleaseMeta_tagErr = ram[131];
  assign io_deq_bits_bits_task_snpHitReleaseMeta_dataErr = ram[130];
  assign io_deq_bits_bits_task_tgtID = ram[129:119];
  assign io_deq_bits_bits_task_srcID = ram[118:108];
  assign io_deq_bits_bits_task_txnID = ram[107:96];
  assign io_deq_bits_bits_task_homeNID = ram[95:85];
  assign io_deq_bits_bits_task_dbID = ram[84:73];
  assign io_deq_bits_bits_task_fwdNID = ram[72:62];
  assign io_deq_bits_bits_task_fwdTxnID = ram[61:50];
  assign io_deq_bits_bits_task_chiOpcode = ram[49:43];
  assign io_deq_bits_bits_task_resp = ram[42:40];
  assign io_deq_bits_bits_task_fwdState = ram[39:37];
  assign io_deq_bits_bits_task_pCrdType = ram[36:33];
  assign io_deq_bits_bits_task_retToSrc = ram[32];
  assign io_deq_bits_bits_task_likelyshared = ram[31];
  assign io_deq_bits_bits_task_expCompAck = ram[30];
  assign io_deq_bits_bits_task_allowRetry = ram[29];
  assign io_deq_bits_bits_task_memAttr_allocate = ram[28];
  assign io_deq_bits_bits_task_memAttr_cacheable = ram[27];
  assign io_deq_bits_bits_task_memAttr_device = ram[26];
  assign io_deq_bits_bits_task_memAttr_ewa = ram[25];
  assign io_deq_bits_bits_task_traceTag = ram[24];
  assign io_deq_bits_idOH = ram[3:0];
endmodule

