// Generated by CIRCT firtool-1.135.0
module sram_array_1p8192x137m137s1h1l2b_l2_dat(
  input          mbist_dft_ram_bypass,
  input          mbist_dft_ram_bp_clken,
  input          RW0_clk,
  input  [12:0]  RW0_addr,
  input          RW0_en,
  input          RW0_wmode,
  input  [136:0] RW0_wdata,
  output [136:0] RW0_rdata
);

  array_8192x137 array_ext (
    .RW0_addr  (RW0_addr),
    .RW0_en    (RW0_en),
    .RW0_clk   (RW0_clk),
    .RW0_wmode (RW0_wmode),
    .RW0_wdata (RW0_wdata),
    .RW0_rdata (RW0_rdata)
  );
endmodule

