// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SRAMTemplate_132(
  input         clock,
  input         reset,
  input         io_r_req_valid,
  input  [5:0]  io_r_req_bits_setIdx,
  output [1:0]  io_r_resp_data_0,
  output [1:0]  io_r_resp_data_1,
  output [1:0]  io_r_resp_data_2,
  output [1:0]  io_r_resp_data_3,
  output [1:0]  io_r_resp_data_4,
  output [1:0]  io_r_resp_data_5,
  output [1:0]  io_r_resp_data_6,
  output [1:0]  io_r_resp_data_7,
  output        io_w_req_ready,
  input         io_w_req_valid,
  input  [5:0]  io_w_req_bits_setIdx,
  input  [1:0]  io_w_req_bits_data_0,
  input  [1:0]  io_w_req_bits_data_1,
  input  [1:0]  io_w_req_bits_data_2,
  input  [1:0]  io_w_req_bits_data_3,
  input  [1:0]  io_w_req_bits_data_4,
  input  [1:0]  io_w_req_bits_data_5,
  input  [1:0]  io_w_req_bits_data_6,
  input  [1:0]  io_w_req_bits_data_7,
  input  [7:0]  io_w_req_bits_waymask,
  input         io_broadcast_ram_hold,
  input         io_broadcast_ram_bypass,
  input         io_broadcast_ram_bp_clken,
  input         io_broadcast_ram_aux_clk,
  input         io_broadcast_ram_aux_ckbp,
  input         io_broadcast_ram_mcp_hold,
  input  [63:0] io_broadcast_ram_ctl,
  input         io_broadcast_cgen,
  output        io_resetDone,
  input  [6:0]  boreChildrenBd_bore_addr,
  input  [6:0]  boreChildrenBd_bore_addr_rd,
  input  [15:0] boreChildrenBd_bore_wdata,
  input  [7:0]  boreChildrenBd_bore_wmask,
  input         boreChildrenBd_bore_re,
  input         boreChildrenBd_bore_we,
  output [15:0] boreChildrenBd_bore_rdata,
  input         boreChildrenBd_bore_ack,
  input         boreChildrenBd_bore_selectedOH,
  input  [7:0]  boreChildrenBd_bore_array
);

  wire        _io_r_req_ready_T_1;
  wire [15:0] _array_RW0_rdata;
  wire        _rcg_out_clock;
  wire [6:0]  mbistBd_addr_rd = boreChildrenBd_bore_addr_rd;
  wire [15:0] mbistBd_wdata = boreChildrenBd_bore_wdata;
  wire [7:0]  mbistBd_wmask = boreChildrenBd_bore_wmask;
  wire        mbistBd_re = boreChildrenBd_bore_re;
  wire        mbistBd_we = boreChildrenBd_bore_we;
  wire        mbistBd_ack = boreChildrenBd_bore_ack;
  wire        mbistBd_selectedOH = boreChildrenBd_bore_selectedOH;
  wire [6:0]  mbistBd_addr = boreChildrenBd_bore_addr;
  wire [7:0]  mbistBd_array = boreChildrenBd_bore_array;
  reg         _resetState;
  reg  [5:0]  _resetSet;
  wire        wckEn = mbistBd_ack ? mbistBd_we : io_w_req_valid | _resetState;
  wire        rckEn =
    mbistBd_ack ? mbistBd_re : ~_resetState & _io_r_req_ready_T_1 & io_r_req_valid;
  wire        finalRamWen = wckEn & ~io_broadcast_ram_hold;
  reg         respReg;
  reg  [15:0] rdataReg;
  wire [15:0] mbistBd_rdata = rdataReg;
  assign _io_r_req_ready_T_1 = ~io_w_req_valid;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      _resetState <= 1'h1;
      _resetSet <= 6'h0;
      respReg <= 1'h0;
    end
    else begin
      _resetState <= ~(_resetState & (&_resetSet)) & _resetState;
      if (_resetState)
        _resetSet <= 6'(_resetSet + 6'h1);
      respReg <= rckEn;
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (respReg)
      rdataReg <= _array_RW0_rdata;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:17];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [4:0] i = 5'h0; i < 5'h12; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        _resetState = _RANDOM[5'h0][0];
        _resetSet = _RANDOM[5'h0][6:1];
        respReg = _RANDOM[5'h1][12];
        rdataReg = _RANDOM[5'h11][28:13];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        _resetState = 1'h1;
        _resetSet = 6'h0;
        respReg = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MbistClockGateCell rcg (
    .clock         (clock),
    .mbist_writeen (wckEn),
    .mbist_readen  (rckEn),
    .mbist_req     (mbistBd_ack),
    .E             (rckEn | wckEn),
    .dft_cgen      (io_broadcast_cgen),
    .out_clock     (_rcg_out_clock)
  );
  sram_array_1p64x16m2s1h0l1b_bpu_tage_useful array (
    .mbist_dft_ram_bypass   (io_broadcast_ram_bypass),
    .mbist_dft_ram_bp_clken (io_broadcast_ram_bp_clken),
    .RW0_clk                (_rcg_out_clock),
    .RW0_addr
      (mbistBd_ack
         ? mbistBd_addr_rd[5:0]
         : finalRamWen
             ? (_resetState ? _resetSet : io_w_req_bits_setIdx)
             : io_r_req_bits_setIdx),
    .RW0_en                 (finalRamWen | rckEn),
    .RW0_wmode              (finalRamWen),
    .RW0_wmask
      (mbistBd_ack
         ? {8{mbistBd_selectedOH}} & mbistBd_wmask
         : _resetState ? 8'hFF : io_w_req_bits_waymask),
    .RW0_wdata
      (mbistBd_ack
         ? mbistBd_wdata
         : _resetState
             ? 16'h0
             : {io_w_req_bits_data_7,
                io_w_req_bits_data_6,
                io_w_req_bits_data_5,
                io_w_req_bits_data_4,
                io_w_req_bits_data_3,
                io_w_req_bits_data_2,
                io_w_req_bits_data_1,
                io_w_req_bits_data_0}),
    .RW0_rdata              (_array_RW0_rdata)
  );
  assign io_r_resp_data_0 = _array_RW0_rdata[1:0];
  assign io_r_resp_data_1 = _array_RW0_rdata[3:2];
  assign io_r_resp_data_2 = _array_RW0_rdata[5:4];
  assign io_r_resp_data_3 = _array_RW0_rdata[7:6];
  assign io_r_resp_data_4 = _array_RW0_rdata[9:8];
  assign io_r_resp_data_5 = _array_RW0_rdata[11:10];
  assign io_r_resp_data_6 = _array_RW0_rdata[13:12];
  assign io_r_resp_data_7 = _array_RW0_rdata[15:14];
  assign io_w_req_ready = ~_resetState;
  assign io_resetDone = ~_resetState;
  assign boreChildrenBd_bore_rdata = mbistBd_rdata;
endmodule

