// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SRAMTemplate(
  input          clock,
  input          reset,
  output         io_r_req_ready,
  input          io_r_req_valid,
  input  [6:0]   io_r_req_bits_setIdx,
  output [68:0]  io_r_resp_data_0,
  output [68:0]  io_r_resp_data_1,
  output         io_w_req_ready,
  input          io_w_req_valid,
  input  [6:0]   io_w_req_bits_setIdx,
  input  [68:0]  io_w_req_bits_data_0,
  input  [68:0]  io_w_req_bits_data_1,
  input  [1:0]   io_w_req_bits_waymask,
  input          io_broadcast_ram_hold,
  input          io_broadcast_ram_bypass,
  input          io_broadcast_ram_bp_clken,
  input          io_broadcast_ram_aux_clk,
  input          io_broadcast_ram_aux_ckbp,
  input          io_broadcast_ram_mcp_hold,
  input  [63:0]  io_broadcast_ram_ctl,
  input          io_broadcast_cgen,
  input  [7:0]   boreChildrenBd_bore_addr,
  input  [7:0]   boreChildrenBd_bore_addr_rd,
  input  [137:0] boreChildrenBd_bore_wdata,
  input  [1:0]   boreChildrenBd_bore_wmask,
  input          boreChildrenBd_bore_re,
  input          boreChildrenBd_bore_we,
  output [137:0] boreChildrenBd_bore_rdata,
  input          boreChildrenBd_bore_ack,
  input          boreChildrenBd_bore_selectedOH,
  input          boreChildrenBd_bore_array
);

  wire         io_r_req_ready_0;
  wire [137:0] _array_RW0_rdata;
  wire         _rcg_out_clock;
  wire [7:0]   mbistBd_addr_rd = boreChildrenBd_bore_addr_rd;
  wire [137:0] mbistBd_wdata = boreChildrenBd_bore_wdata;
  wire [1:0]   mbistBd_wmask = boreChildrenBd_bore_wmask;
  wire         mbistBd_re = boreChildrenBd_bore_re;
  wire         mbistBd_we = boreChildrenBd_bore_we;
  wire         mbistBd_ack = boreChildrenBd_bore_ack;
  wire         mbistBd_selectedOH = boreChildrenBd_bore_selectedOH;
  wire [7:0]   mbistBd_addr = boreChildrenBd_bore_addr;
  wire         mbistBd_array = boreChildrenBd_bore_array;
  reg          _resetState;
  reg  [6:0]   _resetSet;
  wire         wckEn = mbistBd_ack ? mbistBd_we : io_w_req_valid | _resetState;
  wire         rckEn = mbistBd_ack ? mbistBd_re : io_r_req_ready_0 & io_r_req_valid;
  wire         finalRamWen = wckEn & ~io_broadcast_ram_hold;
  reg          respReg;
  reg  [137:0] rdataReg;
  wire [137:0] mbistBd_rdata = rdataReg;
  assign io_r_req_ready_0 = ~_resetState & ~io_w_req_valid;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      _resetState <= 1'h1;
      _resetSet <= 7'h0;
      respReg <= 1'h0;
    end
    else begin
      _resetState <= ~(_resetState & (&_resetSet)) & _resetState;
      if (_resetState)
        _resetSet <= 7'(_resetSet + 7'h1);
      respReg <= rckEn;
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (respReg)
      rdataReg <= _array_RW0_rdata;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:13];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'hE; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        _resetState = _RANDOM[4'h0][0];
        _resetSet = _RANDOM[4'h0][7:1];
        respReg = _RANDOM[4'h5][3];
        rdataReg =
          {_RANDOM[4'h9][31:4],
           _RANDOM[4'hA],
           _RANDOM[4'hB],
           _RANDOM[4'hC],
           _RANDOM[4'hD][13:0]};
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        _resetState = 1'h1;
        _resetSet = 7'h0;
        respReg = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MbistClockGateCell rcg (
    .clock         (clock),
    .mbist_writeen (wckEn),
    .mbist_readen  (rckEn),
    .mbist_req     (mbistBd_ack),
    .E             (rckEn | wckEn),
    .dft_cgen      (io_broadcast_cgen),
    .out_clock     (_rcg_out_clock)
  );
  sram_array_1p128x138m69s1h0l1b_icache_meta array (
    .mbist_dft_ram_bypass   (io_broadcast_ram_bypass),
    .mbist_dft_ram_bp_clken (io_broadcast_ram_bp_clken),
    .RW0_clk                (_rcg_out_clock),
    .RW0_addr
      (mbistBd_ack
         ? mbistBd_addr_rd[6:0]
         : finalRamWen
             ? (_resetState ? _resetSet : io_w_req_bits_setIdx)
             : io_r_req_bits_setIdx),
    .RW0_en                 (finalRamWen | rckEn),
    .RW0_wmode              (finalRamWen),
    .RW0_wmask
      (mbistBd_ack
         ? {2{mbistBd_selectedOH}} & mbistBd_wmask
         : _resetState ? 2'h3 : io_w_req_bits_waymask),
    .RW0_wdata
      (mbistBd_ack
         ? mbistBd_wdata
         : _resetState ? 138'h0 : {io_w_req_bits_data_1, io_w_req_bits_data_0}),
    .RW0_rdata              (_array_RW0_rdata)
  );
  assign io_r_req_ready = io_r_req_ready_0;
  assign io_r_resp_data_0 = _array_RW0_rdata[68:0];
  assign io_r_resp_data_1 = _array_RW0_rdata[137:69];
  assign io_w_req_ready = ~_resetState;
  assign boreChildrenBd_bore_rdata = mbistBd_rdata;
endmodule

