// Generated by CIRCT firtool-1.135.0
module sram_array_1p32x112m56s1h0l1b_bpu_abtb(
  input          mbist_dft_ram_bypass,
  input          mbist_dft_ram_bp_clken,
  input          RW0_clk,
  input  [4:0]   RW0_addr,
  input          RW0_en,
  input          RW0_wmode,
  input  [1:0]   RW0_wmask,
  input  [111:0] RW0_wdata,
  output [111:0] RW0_rdata
);

  wire array_RW0_rdata_MPORT_wmask_1;
  wire array_RW0_rdata_MPORT_wmask_0;
  assign array_RW0_rdata_MPORT_wmask_0 = RW0_wmode & RW0_wmask[0];
  assign array_RW0_rdata_MPORT_wmask_1 = RW0_wmode & RW0_wmask[1];
  array_32x112 array_ext (
    .RW0_addr  (RW0_addr),
    .RW0_en    (RW0_en),
    .RW0_clk   (RW0_clk),
    .RW0_wmode (RW0_wmode & (|RW0_wmask)),
    .RW0_wdata (RW0_wdata),
    .RW0_rdata (RW0_rdata),
    .RW0_wmask ({array_RW0_rdata_MPORT_wmask_1, array_RW0_rdata_MPORT_wmask_0})
  );
endmodule

