// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SRAMTemplate_68(
  input         clock,
  input         reset,
  input         io_r_req_valid,
  input  [7:0]  io_r_req_bits_setIdx,
  output        io_r_resp_data_0_valid,
  output [15:0] io_r_resp_data_0_tag,
  output [1:0]  io_r_resp_data_0_attribute_branchType,
  output [1:0]  io_r_resp_data_0_attribute_rasAction,
  output [3:0]  io_r_resp_data_0_position,
  output [1:0]  io_r_resp_data_0_targetCarry_value,
  output [19:0] io_r_resp_data_0_targetLowerBits,
  output        io_w_req_ready,
  input         io_w_req_valid,
  input  [7:0]  io_w_req_bits_setIdx,
  input         io_w_req_bits_data_0_valid,
  input  [15:0] io_w_req_bits_data_0_tag,
  input  [1:0]  io_w_req_bits_data_0_attribute_branchType,
  input  [1:0]  io_w_req_bits_data_0_attribute_rasAction,
  input  [3:0]  io_w_req_bits_data_0_position,
  input  [1:0]  io_w_req_bits_data_0_targetCarry_value,
  input  [19:0] io_w_req_bits_data_0_targetLowerBits,
  input         io_broadcast_ram_hold,
  input         io_broadcast_ram_bypass,
  input         io_broadcast_ram_bp_clken,
  input         io_broadcast_ram_aux_clk,
  input         io_broadcast_ram_aux_ckbp,
  input         io_broadcast_ram_mcp_hold,
  input  [63:0] io_broadcast_ram_ctl,
  input         io_broadcast_cgen,
  output        io_resetDone,
  input  [8:0]  boreChildrenBd_bore_addr,
  input  [8:0]  boreChildrenBd_bore_addr_rd,
  input  [46:0] boreChildrenBd_bore_wdata,
  input         boreChildrenBd_bore_wmask,
  input         boreChildrenBd_bore_re,
  input         boreChildrenBd_bore_we,
  output [46:0] boreChildrenBd_bore_rdata,
  input         boreChildrenBd_bore_ack,
  input         boreChildrenBd_bore_selectedOH,
  input  [6:0]  boreChildrenBd_bore_array
);

  wire        _io_r_req_ready_T_1;
  wire [46:0] _array_RW0_rdata;
  wire        _rcg_out_clock;
  wire [8:0]  mbistBd_addr_rd = boreChildrenBd_bore_addr_rd;
  wire [46:0] mbistBd_wdata = boreChildrenBd_bore_wdata;
  wire        mbistBd_re = boreChildrenBd_bore_re;
  wire        mbistBd_we = boreChildrenBd_bore_we;
  wire        mbistBd_ack = boreChildrenBd_bore_ack;
  wire        mbistWmask = boreChildrenBd_bore_selectedOH;
  wire [8:0]  mbistBd_addr = boreChildrenBd_bore_addr;
  wire        mbistBd_wmask = boreChildrenBd_bore_wmask;
  wire [6:0]  mbistBd_array = boreChildrenBd_bore_array;
  reg         _resetState;
  reg  [7:0]  _resetSet;
  wire        ren = ~_resetState & _io_r_req_ready_T_1 & io_r_req_valid;
  wire        wckEn = mbistBd_ack ? mbistBd_we : io_w_req_valid | _resetState;
  wire        rckEn = mbistBd_ack ? mbistBd_re : ren;
  wire        finalRamWen = wckEn & ~io_broadcast_ram_hold;
  reg         respReg;
  reg         rdata_last_REG;
  reg  [46:0] rdata_hold_data_0;
  wire [46:0] _rdata_T_0 = rdata_last_REG ? _array_RW0_rdata : rdata_hold_data_0;
  reg  [46:0] rdataReg;
  wire [46:0] mbistBd_rdata = rdataReg;
  assign _io_r_req_ready_T_1 = ~io_w_req_valid;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      _resetState <= 1'h1;
      _resetSet <= 8'h0;
      respReg <= 1'h0;
      rdata_last_REG <= 1'h0;
    end
    else begin
      _resetState <= ~(_resetState & (&_resetSet)) & _resetState;
      if (_resetState)
        _resetSet <= 8'(_resetSet + 8'h1);
      respReg <= rckEn;
      rdata_last_REG <= ren;
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (rdata_last_REG)
      rdata_hold_data_0 <= _array_RW0_rdata;
    if (respReg)
      rdataReg <= _array_RW0_rdata;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:7];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'h8; i += 4'h1) begin
          _RANDOM[i[2:0]] = `RANDOM;
        end
        _resetState = _RANDOM[3'h0][0];
        _resetSet = _RANDOM[3'h0][8:1];
        respReg = _RANDOM[3'h2][10];
        rdata_last_REG = _RANDOM[3'h4][11];
        rdata_hold_data_0 = {_RANDOM[3'h4][31:12], _RANDOM[3'h5][26:0]};
        rdataReg = {_RANDOM[3'h5][31:27], _RANDOM[3'h6], _RANDOM[3'h7][9:0]};
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        _resetState = 1'h1;
        _resetSet = 8'h0;
        respReg = 1'h0;
        rdata_last_REG = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MbistClockGateCell rcg (
    .clock         (clock),
    .mbist_writeen (wckEn),
    .mbist_readen  (rckEn),
    .mbist_req     (mbistBd_ack),
    .E             (rckEn | wckEn),
    .dft_cgen      (io_broadcast_cgen),
    .out_clock     (_rcg_out_clock)
  );
  sram_array_1p256x47m47s1h0l1b_bpu_mbtb_entry array (
    .mbist_dft_ram_bypass   (io_broadcast_ram_bypass),
    .mbist_dft_ram_bp_clken (io_broadcast_ram_bp_clken),
    .RW0_clk                (_rcg_out_clock),
    .RW0_addr
      (mbistBd_ack
         ? mbistBd_addr_rd[7:0]
         : finalRamWen
             ? (_resetState ? _resetSet : io_w_req_bits_setIdx)
             : io_r_req_bits_setIdx),
    .RW0_en                 (finalRamWen | rckEn),
    .RW0_wmode              (finalRamWen),
    .RW0_wdata
      (mbistBd_ack
         ? mbistBd_wdata
         : _resetState
             ? 47'h0
             : {io_w_req_bits_data_0_valid,
                io_w_req_bits_data_0_tag,
                io_w_req_bits_data_0_attribute_branchType,
                io_w_req_bits_data_0_attribute_rasAction,
                io_w_req_bits_data_0_position,
                io_w_req_bits_data_0_targetCarry_value,
                io_w_req_bits_data_0_targetLowerBits}),
    .RW0_rdata              (_array_RW0_rdata)
  );
  assign io_r_resp_data_0_valid = _rdata_T_0[46];
  assign io_r_resp_data_0_tag = _rdata_T_0[45:30];
  assign io_r_resp_data_0_attribute_branchType = _rdata_T_0[29:28];
  assign io_r_resp_data_0_attribute_rasAction = _rdata_T_0[27:26];
  assign io_r_resp_data_0_position = _rdata_T_0[25:22];
  assign io_r_resp_data_0_targetCarry_value = _rdata_T_0[21:20];
  assign io_r_resp_data_0_targetLowerBits = _rdata_T_0[19:0];
  assign io_w_req_ready = ~_resetState;
  assign io_resetDone = ~_resetState;
  assign boreChildrenBd_bore_rdata = mbistBd_rdata;
endmodule

