// Generated by CIRCT firtool-1.135.0
module sram_array_1p128x25m25s1h0l1b_bpu_utage(
  input         mbist_dft_ram_bypass,
  input         mbist_dft_ram_bp_clken,
  input         RW0_clk,
  input  [6:0]  RW0_addr,
  input         RW0_en,
  input         RW0_wmode,
  input  [24:0] RW0_wdata,
  output [24:0] RW0_rdata
);

  array_128x25 array_ext (
    .RW0_addr  (RW0_addr),
    .RW0_en    (RW0_en),
    .RW0_clk   (RW0_clk),
    .RW0_wmode (RW0_wmode),
    .RW0_wdata (RW0_wdata),
    .RW0_rdata (RW0_rdata)
  );
endmodule

