// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SRAMTemplate_246(
  input         clock,
  input         reset,
  input         io_r_req_valid,
  input  [6:0]  io_r_req_bits_setIdx,
  output [5:0]  io_r_resp_data_0_ctr_value,
  output [5:0]  io_r_resp_data_1_ctr_value,
  output [5:0]  io_r_resp_data_2_ctr_value,
  output [5:0]  io_r_resp_data_3_ctr_value,
  output [5:0]  io_r_resp_data_4_ctr_value,
  output [5:0]  io_r_resp_data_5_ctr_value,
  output [5:0]  io_r_resp_data_6_ctr_value,
  output [5:0]  io_r_resp_data_7_ctr_value,
  output        io_w_req_ready,
  input         io_w_req_valid,
  input  [6:0]  io_w_req_bits_setIdx,
  input  [5:0]  io_w_req_bits_data_0_ctr_value,
  input  [5:0]  io_w_req_bits_data_1_ctr_value,
  input  [5:0]  io_w_req_bits_data_2_ctr_value,
  input  [5:0]  io_w_req_bits_data_3_ctr_value,
  input  [5:0]  io_w_req_bits_data_4_ctr_value,
  input  [5:0]  io_w_req_bits_data_5_ctr_value,
  input  [5:0]  io_w_req_bits_data_6_ctr_value,
  input  [5:0]  io_w_req_bits_data_7_ctr_value,
  input  [7:0]  io_w_req_bits_waymask,
  input         io_broadcast_ram_hold,
  input         io_broadcast_ram_bypass,
  input         io_broadcast_ram_bp_clken,
  input         io_broadcast_ram_aux_clk,
  input         io_broadcast_ram_aux_ckbp,
  input         io_broadcast_ram_mcp_hold,
  input  [63:0] io_broadcast_ram_ctl,
  input         io_broadcast_cgen,
  output        io_resetDone,
  input  [7:0]  boreChildrenBd_bore_addr,
  input  [7:0]  boreChildrenBd_bore_addr_rd,
  input  [47:0] boreChildrenBd_bore_wdata,
  input  [7:0]  boreChildrenBd_bore_wmask,
  input         boreChildrenBd_bore_re,
  input         boreChildrenBd_bore_we,
  output [47:0] boreChildrenBd_bore_rdata,
  input         boreChildrenBd_bore_ack,
  input         boreChildrenBd_bore_selectedOH,
  input  [7:0]  boreChildrenBd_bore_array
);

  wire        _io_r_req_ready_T_1;
  wire [47:0] _array_RW0_rdata;
  wire        _rcg_out_clock;
  wire [7:0]  mbistBd_addr_rd = boreChildrenBd_bore_addr_rd;
  wire [47:0] mbistBd_wdata = boreChildrenBd_bore_wdata;
  wire [7:0]  mbistBd_wmask = boreChildrenBd_bore_wmask;
  wire        mbistBd_re = boreChildrenBd_bore_re;
  wire        mbistBd_we = boreChildrenBd_bore_we;
  wire        mbistBd_ack = boreChildrenBd_bore_ack;
  wire        mbistBd_selectedOH = boreChildrenBd_bore_selectedOH;
  wire [7:0]  mbistBd_addr = boreChildrenBd_bore_addr;
  wire [7:0]  mbistBd_array = boreChildrenBd_bore_array;
  reg         _resetState;
  reg  [6:0]  _resetSet;
  wire        ren = ~_resetState & _io_r_req_ready_T_1 & io_r_req_valid;
  wire        wckEn = mbistBd_ack ? mbistBd_we : io_w_req_valid | _resetState;
  wire        rckEn = mbistBd_ack ? mbistBd_re : ren;
  wire        finalRamWen = wckEn & ~io_broadcast_ram_hold;
  reg         respReg;
  reg         rdata_last_REG;
  reg  [5:0]  rdata_hold_data_0;
  reg  [5:0]  rdata_hold_data_1;
  reg  [5:0]  rdata_hold_data_2;
  reg  [5:0]  rdata_hold_data_3;
  reg  [5:0]  rdata_hold_data_4;
  reg  [5:0]  rdata_hold_data_5;
  reg  [5:0]  rdata_hold_data_6;
  reg  [5:0]  rdata_hold_data_7;
  reg  [47:0] rdataReg;
  wire [47:0] mbistBd_rdata = rdataReg;
  assign _io_r_req_ready_T_1 = ~io_w_req_valid;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      _resetState <= 1'h1;
      _resetSet <= 7'h0;
      respReg <= 1'h0;
      rdata_last_REG <= 1'h0;
    end
    else begin
      _resetState <= ~(_resetState & (&_resetSet)) & _resetState;
      if (_resetState)
        _resetSet <= 7'(_resetSet + 7'h1);
      respReg <= rckEn;
      rdata_last_REG <= ren;
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (rdata_last_REG) begin
      rdata_hold_data_0 <= _array_RW0_rdata[5:0];
      rdata_hold_data_1 <= _array_RW0_rdata[11:6];
      rdata_hold_data_2 <= _array_RW0_rdata[17:12];
      rdata_hold_data_3 <= _array_RW0_rdata[23:18];
      rdata_hold_data_4 <= _array_RW0_rdata[29:24];
      rdata_hold_data_5 <= _array_RW0_rdata[35:30];
      rdata_hold_data_6 <= _array_RW0_rdata[41:36];
      rdata_hold_data_7 <= _array_RW0_rdata[47:42];
    end
    if (respReg)
      rdataReg <= _array_RW0_rdata;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:21];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [4:0] i = 5'h0; i < 5'h16; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        _resetState = _RANDOM[5'h0][0];
        _resetSet = _RANDOM[5'h0][7:1];
        respReg = _RANDOM[5'h2][15];
        rdata_last_REG = _RANDOM[5'h12][16];
        rdata_hold_data_0 = _RANDOM[5'h12][22:17];
        rdata_hold_data_1 = _RANDOM[5'h12][28:23];
        rdata_hold_data_2 = {_RANDOM[5'h12][31:29], _RANDOM[5'h13][2:0]};
        rdata_hold_data_3 = _RANDOM[5'h13][8:3];
        rdata_hold_data_4 = _RANDOM[5'h13][14:9];
        rdata_hold_data_5 = _RANDOM[5'h13][20:15];
        rdata_hold_data_6 = _RANDOM[5'h13][26:21];
        rdata_hold_data_7 = {_RANDOM[5'h13][31:27], _RANDOM[5'h14][0]};
        rdataReg = {_RANDOM[5'h14][31:1], _RANDOM[5'h15][16:0]};
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        _resetState = 1'h1;
        _resetSet = 7'h0;
        respReg = 1'h0;
        rdata_last_REG = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MbistClockGateCell rcg (
    .clock         (clock),
    .mbist_writeen (wckEn),
    .mbist_readen  (rckEn),
    .mbist_req     (mbistBd_ack),
    .E             (rckEn | wckEn),
    .dft_cgen      (io_broadcast_cgen),
    .out_clock     (_rcg_out_clock)
  );
  sram_array_1p128x48m6s1h0l1b_bpu_sc array (
    .mbist_dft_ram_bypass   (io_broadcast_ram_bypass),
    .mbist_dft_ram_bp_clken (io_broadcast_ram_bp_clken),
    .RW0_clk                (_rcg_out_clock),
    .RW0_addr
      (mbistBd_ack
         ? mbistBd_addr_rd[6:0]
         : finalRamWen
             ? (_resetState ? _resetSet : io_w_req_bits_setIdx)
             : io_r_req_bits_setIdx),
    .RW0_en                 (finalRamWen | rckEn),
    .RW0_wmode              (finalRamWen),
    .RW0_wmask
      (mbistBd_ack
         ? {8{mbistBd_selectedOH}} & mbistBd_wmask
         : _resetState ? 8'hFF : io_w_req_bits_waymask),
    .RW0_wdata
      (mbistBd_ack
         ? mbistBd_wdata
         : _resetState
             ? 48'h0
             : {io_w_req_bits_data_7_ctr_value,
                io_w_req_bits_data_6_ctr_value,
                io_w_req_bits_data_5_ctr_value,
                io_w_req_bits_data_4_ctr_value,
                io_w_req_bits_data_3_ctr_value,
                io_w_req_bits_data_2_ctr_value,
                io_w_req_bits_data_1_ctr_value,
                io_w_req_bits_data_0_ctr_value}),
    .RW0_rdata              (_array_RW0_rdata)
  );
  assign io_r_resp_data_0_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[5:0] : rdata_hold_data_0;
  assign io_r_resp_data_1_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[11:6] : rdata_hold_data_1;
  assign io_r_resp_data_2_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[17:12] : rdata_hold_data_2;
  assign io_r_resp_data_3_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[23:18] : rdata_hold_data_3;
  assign io_r_resp_data_4_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[29:24] : rdata_hold_data_4;
  assign io_r_resp_data_5_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[35:30] : rdata_hold_data_5;
  assign io_r_resp_data_6_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[41:36] : rdata_hold_data_6;
  assign io_r_resp_data_7_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[47:42] : rdata_hold_data_7;
  assign io_w_req_ready = ~_resetState;
  assign io_resetDone = ~_resetState;
  assign boreChildrenBd_bore_rdata = mbistBd_rdata;
endmodule

