// Generated by CIRCT firtool-1.135.0
module sram_array_1p256x47m47s1h0l1b_bpu_mbtb_entry(
  input         mbist_dft_ram_bypass,
  input         mbist_dft_ram_bp_clken,
  input         RW0_clk,
  input  [7:0]  RW0_addr,
  input         RW0_en,
  input         RW0_wmode,
  input  [46:0] RW0_wdata,
  output [46:0] RW0_rdata
);

  array_256x47 array_ext (
    .RW0_addr  (RW0_addr),
    .RW0_en    (RW0_en),
    .RW0_clk   (RW0_clk),
    .RW0_wmode (RW0_wmode),
    .RW0_wdata (RW0_wdata),
    .RW0_rdata (RW0_rdata)
  );
endmodule

