// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SRAMTemplate_260(
  input          clock,
  input          reset,
  input          io_r_req_valid,
  input  [6:0]   io_r_req_bits_setIdx,
  output [5:0]   io_r_resp_data_0_ctr_value,
  output [5:0]   io_r_resp_data_1_ctr_value,
  output [5:0]   io_r_resp_data_2_ctr_value,
  output [5:0]   io_r_resp_data_3_ctr_value,
  output [5:0]   io_r_resp_data_4_ctr_value,
  output [5:0]   io_r_resp_data_5_ctr_value,
  output [5:0]   io_r_resp_data_6_ctr_value,
  output [5:0]   io_r_resp_data_7_ctr_value,
  output [5:0]   io_r_resp_data_8_ctr_value,
  output [5:0]   io_r_resp_data_9_ctr_value,
  output [5:0]   io_r_resp_data_10_ctr_value,
  output [5:0]   io_r_resp_data_11_ctr_value,
  output [5:0]   io_r_resp_data_12_ctr_value,
  output [5:0]   io_r_resp_data_13_ctr_value,
  output [5:0]   io_r_resp_data_14_ctr_value,
  output [5:0]   io_r_resp_data_15_ctr_value,
  output [5:0]   io_r_resp_data_16_ctr_value,
  output [5:0]   io_r_resp_data_17_ctr_value,
  output [5:0]   io_r_resp_data_18_ctr_value,
  output [5:0]   io_r_resp_data_19_ctr_value,
  output [5:0]   io_r_resp_data_20_ctr_value,
  output [5:0]   io_r_resp_data_21_ctr_value,
  output [5:0]   io_r_resp_data_22_ctr_value,
  output [5:0]   io_r_resp_data_23_ctr_value,
  output [5:0]   io_r_resp_data_24_ctr_value,
  output [5:0]   io_r_resp_data_25_ctr_value,
  output [5:0]   io_r_resp_data_26_ctr_value,
  output [5:0]   io_r_resp_data_27_ctr_value,
  output [5:0]   io_r_resp_data_28_ctr_value,
  output [5:0]   io_r_resp_data_29_ctr_value,
  output [5:0]   io_r_resp_data_30_ctr_value,
  output [5:0]   io_r_resp_data_31_ctr_value,
  output         io_w_req_ready,
  input          io_w_req_valid,
  input  [6:0]   io_w_req_bits_setIdx,
  input  [5:0]   io_w_req_bits_data_0_ctr_value,
  input  [5:0]   io_w_req_bits_data_1_ctr_value,
  input  [5:0]   io_w_req_bits_data_2_ctr_value,
  input  [5:0]   io_w_req_bits_data_3_ctr_value,
  input  [5:0]   io_w_req_bits_data_4_ctr_value,
  input  [5:0]   io_w_req_bits_data_5_ctr_value,
  input  [5:0]   io_w_req_bits_data_6_ctr_value,
  input  [5:0]   io_w_req_bits_data_7_ctr_value,
  input  [5:0]   io_w_req_bits_data_8_ctr_value,
  input  [5:0]   io_w_req_bits_data_9_ctr_value,
  input  [5:0]   io_w_req_bits_data_10_ctr_value,
  input  [5:0]   io_w_req_bits_data_11_ctr_value,
  input  [5:0]   io_w_req_bits_data_12_ctr_value,
  input  [5:0]   io_w_req_bits_data_13_ctr_value,
  input  [5:0]   io_w_req_bits_data_14_ctr_value,
  input  [5:0]   io_w_req_bits_data_15_ctr_value,
  input  [5:0]   io_w_req_bits_data_16_ctr_value,
  input  [5:0]   io_w_req_bits_data_17_ctr_value,
  input  [5:0]   io_w_req_bits_data_18_ctr_value,
  input  [5:0]   io_w_req_bits_data_19_ctr_value,
  input  [5:0]   io_w_req_bits_data_20_ctr_value,
  input  [5:0]   io_w_req_bits_data_21_ctr_value,
  input  [5:0]   io_w_req_bits_data_22_ctr_value,
  input  [5:0]   io_w_req_bits_data_23_ctr_value,
  input  [5:0]   io_w_req_bits_data_24_ctr_value,
  input  [5:0]   io_w_req_bits_data_25_ctr_value,
  input  [5:0]   io_w_req_bits_data_26_ctr_value,
  input  [5:0]   io_w_req_bits_data_27_ctr_value,
  input  [5:0]   io_w_req_bits_data_28_ctr_value,
  input  [5:0]   io_w_req_bits_data_29_ctr_value,
  input  [5:0]   io_w_req_bits_data_30_ctr_value,
  input  [5:0]   io_w_req_bits_data_31_ctr_value,
  input  [31:0]  io_w_req_bits_waymask,
  input          io_broadcast_ram_hold,
  input          io_broadcast_ram_bypass,
  input          io_broadcast_ram_bp_clken,
  input          io_broadcast_ram_aux_clk,
  input          io_broadcast_ram_aux_ckbp,
  input          io_broadcast_ram_mcp_hold,
  input  [63:0]  io_broadcast_ram_ctl,
  input          io_broadcast_cgen,
  output         io_resetDone,
  input  [7:0]   boreChildrenBd_bore_addr,
  input  [7:0]   boreChildrenBd_bore_addr_rd,
  input  [191:0] boreChildrenBd_bore_wdata,
  input  [31:0]  boreChildrenBd_bore_wmask,
  input          boreChildrenBd_bore_re,
  input          boreChildrenBd_bore_we,
  output [191:0] boreChildrenBd_bore_rdata,
  input          boreChildrenBd_bore_ack,
  input          boreChildrenBd_bore_selectedOH,
  input  [8:0]   boreChildrenBd_bore_array
);

  wire         _io_r_req_ready_T_1;
  wire [191:0] _array_RW0_rdata;
  wire         _rcg_out_clock;
  wire [7:0]   mbistBd_addr_rd = boreChildrenBd_bore_addr_rd;
  wire [191:0] mbistBd_wdata = boreChildrenBd_bore_wdata;
  wire [31:0]  mbistBd_wmask = boreChildrenBd_bore_wmask;
  wire         mbistBd_re = boreChildrenBd_bore_re;
  wire         mbistBd_we = boreChildrenBd_bore_we;
  wire         mbistBd_ack = boreChildrenBd_bore_ack;
  wire         mbistBd_selectedOH = boreChildrenBd_bore_selectedOH;
  wire [7:0]   mbistBd_addr = boreChildrenBd_bore_addr;
  wire [8:0]   mbistBd_array = boreChildrenBd_bore_array;
  reg          _resetState;
  reg  [6:0]   _resetSet;
  wire         ren = ~_resetState & _io_r_req_ready_T_1 & io_r_req_valid;
  wire         wckEn = mbistBd_ack ? mbistBd_we : io_w_req_valid | _resetState;
  wire         rckEn = mbistBd_ack ? mbistBd_re : ren;
  wire         finalRamWen = wckEn & ~io_broadcast_ram_hold;
  reg          respReg;
  reg          rdata_last_REG;
  reg  [5:0]   rdata_hold_data_0;
  reg  [5:0]   rdata_hold_data_1;
  reg  [5:0]   rdata_hold_data_2;
  reg  [5:0]   rdata_hold_data_3;
  reg  [5:0]   rdata_hold_data_4;
  reg  [5:0]   rdata_hold_data_5;
  reg  [5:0]   rdata_hold_data_6;
  reg  [5:0]   rdata_hold_data_7;
  reg  [5:0]   rdata_hold_data_8;
  reg  [5:0]   rdata_hold_data_9;
  reg  [5:0]   rdata_hold_data_10;
  reg  [5:0]   rdata_hold_data_11;
  reg  [5:0]   rdata_hold_data_12;
  reg  [5:0]   rdata_hold_data_13;
  reg  [5:0]   rdata_hold_data_14;
  reg  [5:0]   rdata_hold_data_15;
  reg  [5:0]   rdata_hold_data_16;
  reg  [5:0]   rdata_hold_data_17;
  reg  [5:0]   rdata_hold_data_18;
  reg  [5:0]   rdata_hold_data_19;
  reg  [5:0]   rdata_hold_data_20;
  reg  [5:0]   rdata_hold_data_21;
  reg  [5:0]   rdata_hold_data_22;
  reg  [5:0]   rdata_hold_data_23;
  reg  [5:0]   rdata_hold_data_24;
  reg  [5:0]   rdata_hold_data_25;
  reg  [5:0]   rdata_hold_data_26;
  reg  [5:0]   rdata_hold_data_27;
  reg  [5:0]   rdata_hold_data_28;
  reg  [5:0]   rdata_hold_data_29;
  reg  [5:0]   rdata_hold_data_30;
  reg  [5:0]   rdata_hold_data_31;
  reg  [191:0] rdataReg;
  wire [191:0] mbistBd_rdata = rdataReg;
  assign _io_r_req_ready_T_1 = ~io_w_req_valid;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      _resetState <= 1'h1;
      _resetSet <= 7'h0;
      respReg <= 1'h0;
      rdata_last_REG <= 1'h0;
    end
    else begin
      _resetState <= ~(_resetState & (&_resetSet)) & _resetState;
      if (_resetState)
        _resetSet <= 7'(_resetSet + 7'h1);
      respReg <= rckEn;
      rdata_last_REG <= ren;
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (rdata_last_REG) begin
      rdata_hold_data_0 <= _array_RW0_rdata[5:0];
      rdata_hold_data_1 <= _array_RW0_rdata[11:6];
      rdata_hold_data_2 <= _array_RW0_rdata[17:12];
      rdata_hold_data_3 <= _array_RW0_rdata[23:18];
      rdata_hold_data_4 <= _array_RW0_rdata[29:24];
      rdata_hold_data_5 <= _array_RW0_rdata[35:30];
      rdata_hold_data_6 <= _array_RW0_rdata[41:36];
      rdata_hold_data_7 <= _array_RW0_rdata[47:42];
      rdata_hold_data_8 <= _array_RW0_rdata[53:48];
      rdata_hold_data_9 <= _array_RW0_rdata[59:54];
      rdata_hold_data_10 <= _array_RW0_rdata[65:60];
      rdata_hold_data_11 <= _array_RW0_rdata[71:66];
      rdata_hold_data_12 <= _array_RW0_rdata[77:72];
      rdata_hold_data_13 <= _array_RW0_rdata[83:78];
      rdata_hold_data_14 <= _array_RW0_rdata[89:84];
      rdata_hold_data_15 <= _array_RW0_rdata[95:90];
      rdata_hold_data_16 <= _array_RW0_rdata[101:96];
      rdata_hold_data_17 <= _array_RW0_rdata[107:102];
      rdata_hold_data_18 <= _array_RW0_rdata[113:108];
      rdata_hold_data_19 <= _array_RW0_rdata[119:114];
      rdata_hold_data_20 <= _array_RW0_rdata[125:120];
      rdata_hold_data_21 <= _array_RW0_rdata[131:126];
      rdata_hold_data_22 <= _array_RW0_rdata[137:132];
      rdata_hold_data_23 <= _array_RW0_rdata[143:138];
      rdata_hold_data_24 <= _array_RW0_rdata[149:144];
      rdata_hold_data_25 <= _array_RW0_rdata[155:150];
      rdata_hold_data_26 <= _array_RW0_rdata[161:156];
      rdata_hold_data_27 <= _array_RW0_rdata[167:162];
      rdata_hold_data_28 <= _array_RW0_rdata[173:168];
      rdata_hold_data_29 <= _array_RW0_rdata[179:174];
      rdata_hold_data_30 <= _array_RW0_rdata[185:180];
      rdata_hold_data_31 <= _array_RW0_rdata[191:186];
    end
    if (respReg)
      rdataReg <= _array_RW0_rdata;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:83];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [6:0] i = 7'h0; i < 7'h54; i += 7'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        _resetState = _RANDOM[7'h0][0];
        _resetSet = _RANDOM[7'h0][7:1];
        respReg = _RANDOM[7'h7][23];
        rdata_last_REG = _RANDOM[7'h47][24];
        rdata_hold_data_0 = _RANDOM[7'h47][30:25];
        rdata_hold_data_1 = {_RANDOM[7'h47][31], _RANDOM[7'h48][4:0]};
        rdata_hold_data_2 = _RANDOM[7'h48][10:5];
        rdata_hold_data_3 = _RANDOM[7'h48][16:11];
        rdata_hold_data_4 = _RANDOM[7'h48][22:17];
        rdata_hold_data_5 = _RANDOM[7'h48][28:23];
        rdata_hold_data_6 = {_RANDOM[7'h48][31:29], _RANDOM[7'h49][2:0]};
        rdata_hold_data_7 = _RANDOM[7'h49][8:3];
        rdata_hold_data_8 = _RANDOM[7'h49][14:9];
        rdata_hold_data_9 = _RANDOM[7'h49][20:15];
        rdata_hold_data_10 = _RANDOM[7'h49][26:21];
        rdata_hold_data_11 = {_RANDOM[7'h49][31:27], _RANDOM[7'h4A][0]};
        rdata_hold_data_12 = _RANDOM[7'h4A][6:1];
        rdata_hold_data_13 = _RANDOM[7'h4A][12:7];
        rdata_hold_data_14 = _RANDOM[7'h4A][18:13];
        rdata_hold_data_15 = _RANDOM[7'h4A][24:19];
        rdata_hold_data_16 = _RANDOM[7'h4A][30:25];
        rdata_hold_data_17 = {_RANDOM[7'h4A][31], _RANDOM[7'h4B][4:0]};
        rdata_hold_data_18 = _RANDOM[7'h4B][10:5];
        rdata_hold_data_19 = _RANDOM[7'h4B][16:11];
        rdata_hold_data_20 = _RANDOM[7'h4B][22:17];
        rdata_hold_data_21 = _RANDOM[7'h4B][28:23];
        rdata_hold_data_22 = {_RANDOM[7'h4B][31:29], _RANDOM[7'h4C][2:0]};
        rdata_hold_data_23 = _RANDOM[7'h4C][8:3];
        rdata_hold_data_24 = _RANDOM[7'h4C][14:9];
        rdata_hold_data_25 = _RANDOM[7'h4C][20:15];
        rdata_hold_data_26 = _RANDOM[7'h4C][26:21];
        rdata_hold_data_27 = {_RANDOM[7'h4C][31:27], _RANDOM[7'h4D][0]};
        rdata_hold_data_28 = _RANDOM[7'h4D][6:1];
        rdata_hold_data_29 = _RANDOM[7'h4D][12:7];
        rdata_hold_data_30 = _RANDOM[7'h4D][18:13];
        rdata_hold_data_31 = _RANDOM[7'h4D][24:19];
        rdataReg =
          {_RANDOM[7'h4D][31:25],
           _RANDOM[7'h4E],
           _RANDOM[7'h4F],
           _RANDOM[7'h50],
           _RANDOM[7'h51],
           _RANDOM[7'h52],
           _RANDOM[7'h53][24:0]};
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        _resetState = 1'h1;
        _resetSet = 7'h0;
        respReg = 1'h0;
        rdata_last_REG = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MbistClockGateCell rcg (
    .clock         (clock),
    .mbist_writeen (wckEn),
    .mbist_readen  (rckEn),
    .mbist_req     (mbistBd_ack),
    .E             (rckEn | wckEn),
    .dft_cgen      (io_broadcast_cgen),
    .out_clock     (_rcg_out_clock)
  );
  sram_array_1p128x192m6s1h0l1b_bpu_sc array (
    .mbist_dft_ram_bypass   (io_broadcast_ram_bypass),
    .mbist_dft_ram_bp_clken (io_broadcast_ram_bp_clken),
    .RW0_clk                (_rcg_out_clock),
    .RW0_addr
      (mbistBd_ack
         ? mbistBd_addr_rd[6:0]
         : finalRamWen
             ? (_resetState ? _resetSet : io_w_req_bits_setIdx)
             : io_r_req_bits_setIdx),
    .RW0_en                 (finalRamWen | rckEn),
    .RW0_wmode              (finalRamWen),
    .RW0_wmask
      (mbistBd_ack
         ? {32{mbistBd_selectedOH}} & mbistBd_wmask
         : _resetState ? 32'hFFFFFFFF : io_w_req_bits_waymask),
    .RW0_wdata
      (mbistBd_ack
         ? mbistBd_wdata
         : _resetState
             ? 192'h0
             : {io_w_req_bits_data_31_ctr_value,
                io_w_req_bits_data_30_ctr_value,
                io_w_req_bits_data_29_ctr_value,
                io_w_req_bits_data_28_ctr_value,
                io_w_req_bits_data_27_ctr_value,
                io_w_req_bits_data_26_ctr_value,
                io_w_req_bits_data_25_ctr_value,
                io_w_req_bits_data_24_ctr_value,
                io_w_req_bits_data_23_ctr_value,
                io_w_req_bits_data_22_ctr_value,
                io_w_req_bits_data_21_ctr_value,
                io_w_req_bits_data_20_ctr_value,
                io_w_req_bits_data_19_ctr_value,
                io_w_req_bits_data_18_ctr_value,
                io_w_req_bits_data_17_ctr_value,
                io_w_req_bits_data_16_ctr_value,
                io_w_req_bits_data_15_ctr_value,
                io_w_req_bits_data_14_ctr_value,
                io_w_req_bits_data_13_ctr_value,
                io_w_req_bits_data_12_ctr_value,
                io_w_req_bits_data_11_ctr_value,
                io_w_req_bits_data_10_ctr_value,
                io_w_req_bits_data_9_ctr_value,
                io_w_req_bits_data_8_ctr_value,
                io_w_req_bits_data_7_ctr_value,
                io_w_req_bits_data_6_ctr_value,
                io_w_req_bits_data_5_ctr_value,
                io_w_req_bits_data_4_ctr_value,
                io_w_req_bits_data_3_ctr_value,
                io_w_req_bits_data_2_ctr_value,
                io_w_req_bits_data_1_ctr_value,
                io_w_req_bits_data_0_ctr_value}),
    .RW0_rdata              (_array_RW0_rdata)
  );
  assign io_r_resp_data_0_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[5:0] : rdata_hold_data_0;
  assign io_r_resp_data_1_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[11:6] : rdata_hold_data_1;
  assign io_r_resp_data_2_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[17:12] : rdata_hold_data_2;
  assign io_r_resp_data_3_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[23:18] : rdata_hold_data_3;
  assign io_r_resp_data_4_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[29:24] : rdata_hold_data_4;
  assign io_r_resp_data_5_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[35:30] : rdata_hold_data_5;
  assign io_r_resp_data_6_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[41:36] : rdata_hold_data_6;
  assign io_r_resp_data_7_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[47:42] : rdata_hold_data_7;
  assign io_r_resp_data_8_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[53:48] : rdata_hold_data_8;
  assign io_r_resp_data_9_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[59:54] : rdata_hold_data_9;
  assign io_r_resp_data_10_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[65:60] : rdata_hold_data_10;
  assign io_r_resp_data_11_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[71:66] : rdata_hold_data_11;
  assign io_r_resp_data_12_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[77:72] : rdata_hold_data_12;
  assign io_r_resp_data_13_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[83:78] : rdata_hold_data_13;
  assign io_r_resp_data_14_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[89:84] : rdata_hold_data_14;
  assign io_r_resp_data_15_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[95:90] : rdata_hold_data_15;
  assign io_r_resp_data_16_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[101:96] : rdata_hold_data_16;
  assign io_r_resp_data_17_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[107:102] : rdata_hold_data_17;
  assign io_r_resp_data_18_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[113:108] : rdata_hold_data_18;
  assign io_r_resp_data_19_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[119:114] : rdata_hold_data_19;
  assign io_r_resp_data_20_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[125:120] : rdata_hold_data_20;
  assign io_r_resp_data_21_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[131:126] : rdata_hold_data_21;
  assign io_r_resp_data_22_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[137:132] : rdata_hold_data_22;
  assign io_r_resp_data_23_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[143:138] : rdata_hold_data_23;
  assign io_r_resp_data_24_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[149:144] : rdata_hold_data_24;
  assign io_r_resp_data_25_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[155:150] : rdata_hold_data_25;
  assign io_r_resp_data_26_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[161:156] : rdata_hold_data_26;
  assign io_r_resp_data_27_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[167:162] : rdata_hold_data_27;
  assign io_r_resp_data_28_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[173:168] : rdata_hold_data_28;
  assign io_r_resp_data_29_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[179:174] : rdata_hold_data_29;
  assign io_r_resp_data_30_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[185:180] : rdata_hold_data_30;
  assign io_r_resp_data_31_ctr_value =
    rdata_last_REG ? _array_RW0_rdata[191:186] : rdata_hold_data_31;
  assign io_w_req_ready = ~_resetState;
  assign io_resetDone = ~_resetState;
  assign boreChildrenBd_bore_rdata = mbistBd_rdata;
endmodule

