// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TwoLevelRRArbiter_32(
  input  clock,
  input  reset,
  output io_in_0_ready,
  input  io_in_0_valid,
  output io_in_1_ready,
  input  io_in_1_valid,
  output io_in_2_ready,
  input  io_in_2_valid,
  output io_in_3_ready,
  input  io_in_3_valid,
  output io_in_4_ready,
  input  io_in_4_valid,
  output io_in_5_ready,
  input  io_in_5_valid,
  output io_in_6_ready,
  input  io_in_6_valid,
  output io_in_7_ready,
  input  io_in_7_valid,
  output io_in_8_ready,
  input  io_in_8_valid,
  output io_in_9_ready,
  input  io_in_9_valid,
  output io_in_10_ready,
  input  io_in_10_valid,
  output io_in_11_ready,
  input  io_in_11_valid,
  output io_in_12_ready,
  input  io_in_12_valid,
  output io_in_13_ready,
  input  io_in_13_valid,
  output io_in_14_ready,
  input  io_in_14_valid,
  output io_in_15_ready,
  input  io_in_15_valid,
  output io_in_16_ready,
  input  io_in_16_valid,
  output io_in_17_ready,
  input  io_in_17_valid,
  output io_in_18_ready,
  input  io_in_18_valid,
  output io_in_19_ready,
  input  io_in_19_valid,
  output io_in_20_ready,
  input  io_in_20_valid,
  output io_in_21_ready,
  input  io_in_21_valid,
  output io_in_22_ready,
  input  io_in_22_valid,
  output io_in_23_ready,
  input  io_in_23_valid,
  output io_in_24_ready,
  input  io_in_24_valid,
  output io_in_25_ready,
  input  io_in_25_valid,
  output io_in_26_ready,
  input  io_in_26_valid,
  output io_in_27_ready,
  input  io_in_27_valid,
  output io_in_28_ready,
  input  io_in_28_valid,
  output io_in_29_ready,
  input  io_in_29_valid,
  output io_in_30_ready,
  input  io_in_30_valid,
  output io_in_31_ready,
  input  io_in_31_valid,
  output io_in_32_ready,
  input  io_in_32_valid,
  output io_in_33_ready,
  input  io_in_33_valid,
  output io_in_34_ready,
  input  io_in_34_valid,
  output io_in_35_ready,
  input  io_in_35_valid,
  output io_in_36_ready,
  input  io_in_36_valid,
  output io_in_37_ready,
  input  io_in_37_valid,
  output io_in_38_ready,
  input  io_in_38_valid,
  output io_in_39_ready,
  input  io_in_39_valid,
  output io_in_40_ready,
  input  io_in_40_valid,
  output io_in_41_ready,
  input  io_in_41_valid,
  output io_in_42_ready,
  input  io_in_42_valid,
  output io_in_43_ready,
  input  io_in_43_valid,
  output io_in_44_ready,
  input  io_in_44_valid,
  output io_in_45_ready,
  input  io_in_45_valid,
  output io_in_46_ready,
  input  io_in_46_valid,
  output io_in_47_ready,
  input  io_in_47_valid,
  output io_in_48_ready,
  input  io_in_48_valid,
  output io_in_49_ready,
  input  io_in_49_valid,
  output io_in_50_ready,
  input  io_in_50_valid,
  output io_in_51_ready,
  input  io_in_51_valid,
  output io_in_52_ready,
  input  io_in_52_valid,
  output io_in_53_ready,
  input  io_in_53_valid,
  output io_in_54_ready,
  input  io_in_54_valid,
  output io_in_55_ready,
  input  io_in_55_valid,
  output io_in_56_ready,
  input  io_in_56_valid,
  output io_in_57_ready,
  input  io_in_57_valid,
  output io_in_58_ready,
  input  io_in_58_valid,
  output io_in_59_ready,
  input  io_in_59_valid,
  output io_in_60_ready,
  input  io_in_60_valid,
  output io_in_61_ready,
  input  io_in_61_valid,
  output io_in_62_ready,
  input  io_in_62_valid,
  output io_in_63_ready,
  input  io_in_63_valid,
  output io_in_64_ready,
  input  io_in_64_valid,
  output io_in_65_ready,
  input  io_in_65_valid,
  output io_in_66_ready,
  input  io_in_66_valid,
  output io_in_67_ready,
  input  io_in_67_valid,
  output io_in_68_ready,
  input  io_in_68_valid,
  output io_in_69_ready,
  input  io_in_69_valid,
  output io_in_70_ready,
  input  io_in_70_valid,
  output io_in_71_ready,
  input  io_in_71_valid,
  output io_in_72_ready,
  input  io_in_72_valid,
  output io_in_73_ready,
  input  io_in_73_valid,
  output io_in_74_ready,
  input  io_in_74_valid,
  output io_in_75_ready,
  input  io_in_75_valid,
  output io_in_76_ready,
  input  io_in_76_valid,
  output io_in_77_ready,
  input  io_in_77_valid,
  output io_in_78_ready,
  input  io_in_78_valid,
  output io_in_79_ready,
  input  io_in_79_valid,
  output io_out_valid
);

  wire _highArb_io_out_valid;
  wire _lowArb_io_out_valid;
  reg  selLow;
  wire finalSelLow =
    _lowArb_io_out_valid & _highArb_io_out_valid & selLow | _lowArb_io_out_valid
    & ~_highArb_io_out_valid;
  wire io_out_valid_0 = _lowArb_io_out_valid | _highArb_io_out_valid;
  always @(posedge clock or posedge reset) begin
    if (reset)
      selLow <= 1'h0;
    else if (io_out_valid_0)
      selLow <= finalSelLow ? ~_highArb_io_out_valid : _lowArb_io_out_valid;
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        selLow = _RANDOM[/*Zero width*/ 1'b0][0];
      `endif // RANDOMIZE_REG_INIT
      if (reset)
        selLow = 1'h0;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  FastArbiter_68 lowArb (
    .clock          (clock),
    .reset          (reset),
    .io_in_0_ready  (io_in_0_ready),
    .io_in_0_valid  (io_in_0_valid),
    .io_in_1_ready  (io_in_1_ready),
    .io_in_1_valid  (io_in_1_valid),
    .io_in_2_ready  (io_in_2_ready),
    .io_in_2_valid  (io_in_2_valid),
    .io_in_3_ready  (io_in_3_ready),
    .io_in_3_valid  (io_in_3_valid),
    .io_in_4_ready  (io_in_4_ready),
    .io_in_4_valid  (io_in_4_valid),
    .io_in_5_ready  (io_in_5_ready),
    .io_in_5_valid  (io_in_5_valid),
    .io_in_6_ready  (io_in_6_ready),
    .io_in_6_valid  (io_in_6_valid),
    .io_in_7_ready  (io_in_7_ready),
    .io_in_7_valid  (io_in_7_valid),
    .io_in_8_ready  (io_in_8_ready),
    .io_in_8_valid  (io_in_8_valid),
    .io_in_9_ready  (io_in_9_ready),
    .io_in_9_valid  (io_in_9_valid),
    .io_in_10_ready (io_in_10_ready),
    .io_in_10_valid (io_in_10_valid),
    .io_in_11_ready (io_in_11_ready),
    .io_in_11_valid (io_in_11_valid),
    .io_in_12_ready (io_in_12_ready),
    .io_in_12_valid (io_in_12_valid),
    .io_in_13_ready (io_in_13_ready),
    .io_in_13_valid (io_in_13_valid),
    .io_in_14_ready (io_in_14_ready),
    .io_in_14_valid (io_in_14_valid),
    .io_in_15_ready (io_in_15_ready),
    .io_in_15_valid (io_in_15_valid),
    .io_in_16_ready (io_in_16_ready),
    .io_in_16_valid (io_in_16_valid),
    .io_in_17_ready (io_in_17_ready),
    .io_in_17_valid (io_in_17_valid),
    .io_in_18_ready (io_in_18_ready),
    .io_in_18_valid (io_in_18_valid),
    .io_in_19_ready (io_in_19_ready),
    .io_in_19_valid (io_in_19_valid),
    .io_in_20_ready (io_in_20_ready),
    .io_in_20_valid (io_in_20_valid),
    .io_in_21_ready (io_in_21_ready),
    .io_in_21_valid (io_in_21_valid),
    .io_in_22_ready (io_in_22_ready),
    .io_in_22_valid (io_in_22_valid),
    .io_in_23_ready (io_in_23_ready),
    .io_in_23_valid (io_in_23_valid),
    .io_in_24_ready (io_in_24_ready),
    .io_in_24_valid (io_in_24_valid),
    .io_in_25_ready (io_in_25_ready),
    .io_in_25_valid (io_in_25_valid),
    .io_in_26_ready (io_in_26_ready),
    .io_in_26_valid (io_in_26_valid),
    .io_in_27_ready (io_in_27_ready),
    .io_in_27_valid (io_in_27_valid),
    .io_in_28_ready (io_in_28_ready),
    .io_in_28_valid (io_in_28_valid),
    .io_in_29_ready (io_in_29_ready),
    .io_in_29_valid (io_in_29_valid),
    .io_in_30_ready (io_in_30_ready),
    .io_in_30_valid (io_in_30_valid),
    .io_in_31_ready (io_in_31_ready),
    .io_in_31_valid (io_in_31_valid),
    .io_in_32_ready (io_in_32_ready),
    .io_in_32_valid (io_in_32_valid),
    .io_in_33_ready (io_in_33_ready),
    .io_in_33_valid (io_in_33_valid),
    .io_in_34_ready (io_in_34_ready),
    .io_in_34_valid (io_in_34_valid),
    .io_in_35_ready (io_in_35_ready),
    .io_in_35_valid (io_in_35_valid),
    .io_in_36_ready (io_in_36_ready),
    .io_in_36_valid (io_in_36_valid),
    .io_in_37_ready (io_in_37_ready),
    .io_in_37_valid (io_in_37_valid),
    .io_in_38_ready (io_in_38_ready),
    .io_in_38_valid (io_in_38_valid),
    .io_in_39_ready (io_in_39_ready),
    .io_in_39_valid (io_in_39_valid),
    .io_out_ready   (finalSelLow),
    .io_out_valid   (_lowArb_io_out_valid)
  );
  FastArbiter_68 highArb (
    .clock          (clock),
    .reset          (reset),
    .io_in_0_ready  (io_in_40_ready),
    .io_in_0_valid  (io_in_40_valid),
    .io_in_1_ready  (io_in_41_ready),
    .io_in_1_valid  (io_in_41_valid),
    .io_in_2_ready  (io_in_42_ready),
    .io_in_2_valid  (io_in_42_valid),
    .io_in_3_ready  (io_in_43_ready),
    .io_in_3_valid  (io_in_43_valid),
    .io_in_4_ready  (io_in_44_ready),
    .io_in_4_valid  (io_in_44_valid),
    .io_in_5_ready  (io_in_45_ready),
    .io_in_5_valid  (io_in_45_valid),
    .io_in_6_ready  (io_in_46_ready),
    .io_in_6_valid  (io_in_46_valid),
    .io_in_7_ready  (io_in_47_ready),
    .io_in_7_valid  (io_in_47_valid),
    .io_in_8_ready  (io_in_48_ready),
    .io_in_8_valid  (io_in_48_valid),
    .io_in_9_ready  (io_in_49_ready),
    .io_in_9_valid  (io_in_49_valid),
    .io_in_10_ready (io_in_50_ready),
    .io_in_10_valid (io_in_50_valid),
    .io_in_11_ready (io_in_51_ready),
    .io_in_11_valid (io_in_51_valid),
    .io_in_12_ready (io_in_52_ready),
    .io_in_12_valid (io_in_52_valid),
    .io_in_13_ready (io_in_53_ready),
    .io_in_13_valid (io_in_53_valid),
    .io_in_14_ready (io_in_54_ready),
    .io_in_14_valid (io_in_54_valid),
    .io_in_15_ready (io_in_55_ready),
    .io_in_15_valid (io_in_55_valid),
    .io_in_16_ready (io_in_56_ready),
    .io_in_16_valid (io_in_56_valid),
    .io_in_17_ready (io_in_57_ready),
    .io_in_17_valid (io_in_57_valid),
    .io_in_18_ready (io_in_58_ready),
    .io_in_18_valid (io_in_58_valid),
    .io_in_19_ready (io_in_59_ready),
    .io_in_19_valid (io_in_59_valid),
    .io_in_20_ready (io_in_60_ready),
    .io_in_20_valid (io_in_60_valid),
    .io_in_21_ready (io_in_61_ready),
    .io_in_21_valid (io_in_61_valid),
    .io_in_22_ready (io_in_62_ready),
    .io_in_22_valid (io_in_62_valid),
    .io_in_23_ready (io_in_63_ready),
    .io_in_23_valid (io_in_63_valid),
    .io_in_24_ready (io_in_64_ready),
    .io_in_24_valid (io_in_64_valid),
    .io_in_25_ready (io_in_65_ready),
    .io_in_25_valid (io_in_65_valid),
    .io_in_26_ready (io_in_66_ready),
    .io_in_26_valid (io_in_66_valid),
    .io_in_27_ready (io_in_67_ready),
    .io_in_27_valid (io_in_67_valid),
    .io_in_28_ready (io_in_68_ready),
    .io_in_28_valid (io_in_68_valid),
    .io_in_29_ready (io_in_69_ready),
    .io_in_29_valid (io_in_69_valid),
    .io_in_30_ready (io_in_70_ready),
    .io_in_30_valid (io_in_70_valid),
    .io_in_31_ready (io_in_71_ready),
    .io_in_31_valid (io_in_71_valid),
    .io_in_32_ready (io_in_72_ready),
    .io_in_32_valid (io_in_72_valid),
    .io_in_33_ready (io_in_73_ready),
    .io_in_33_valid (io_in_73_valid),
    .io_in_34_ready (io_in_74_ready),
    .io_in_34_valid (io_in_74_valid),
    .io_in_35_ready (io_in_75_ready),
    .io_in_35_valid (io_in_75_valid),
    .io_in_36_ready (io_in_76_ready),
    .io_in_36_valid (io_in_76_valid),
    .io_in_37_ready (io_in_77_ready),
    .io_in_37_valid (io_in_77_valid),
    .io_in_38_ready (io_in_78_ready),
    .io_in_38_valid (io_in_78_valid),
    .io_in_39_ready (io_in_79_ready),
    .io_in_39_valid (io_in_79_valid),
    .io_out_ready   (~finalSelLow),
    .io_out_valid   (_highArb_io_out_valid)
  );
  assign io_out_valid = io_out_valid_0;
endmodule

